package froq

// FaceBase craniofacial research datasets (DERIVA catalog).
// Auto-generated by normalizers/from_facebase.py — do not hand-edit.

genes: "AXIN2": {
	_in_facebase: true
	facebase_id:  "FB00001167"
	facebase_datasets: [
		{title: "Gene summary for Axin2", species: "Mus musculus", assay_type: "gene summary"},
	]
}

genes: "BMP4": {
	_in_facebase: true
	facebase_id:  "FB00001156"
	facebase_datasets: [
		{title: "Gene summary for BMP4", species: "Mus musculus", assay_type: "gene summary"},
		{title: "Gene summary for BMP4", species: "Mus musculus", assay_type: "gene summary"},
	]
}

genes: "CTNNB1": {
	_in_facebase: true
	facebase_id:  "FB00001131"
	facebase_datasets: [
		{title: "Gene summary for Ctnnb1", species: "Mus musculus", assay_type: "gene summary"},
	]
}

genes: "DLX2": {
	_in_facebase: true
	facebase_id:  "FB00001164"
	facebase_datasets: [
		{title: "Gene summary for Dlx2", species: "Mus musculus", assay_type: "gene summary"},
	]
}

genes: "DLX3": {
	_in_facebase: true
	facebase_id:  "FB00001165"
	facebase_datasets: [
		{title: "Gene summary for Dlx3", species: "Mus musculus", assay_type: "gene summary"},
	]
}

genes: "DLX5": {
	_in_facebase: true
	facebase_id:  "FB00001081"
	facebase_datasets: [
		{title: "RNAseq of Dlx5-/- and littermate controls at E14.5", species: "Mus musculus", assay_type: "RNA-seq"},
		{title: "Gene summary for Dlx5", species: "Mus musculus", assay_type: "gene summary"},
	]
}

genes: "FGF8": {
	_in_facebase: true
	facebase_id:  "FB00001134"
	facebase_datasets: [
		{title: "Gene summary for Fgf8", species: "Mus musculus", assay_type: "gene summary"},
		{title: "Images of P0 neonates and E10.5 mouse embryos from two different Fgf8 allelic series", species: "Mus musculus", assay_type: "other"},
	]
}

genes: "FGFR1": {
	_in_facebase: true
	facebase_id:  "FB00001137"
	facebase_datasets: [
		{title: "Gene summary for Fgfr1", species: "Mus musculus", assay_type: "gene summary"},
	]
}

genes: "FGFR2": {
	_in_facebase: true
	facebase_id:  "FB00001112"
	facebase_datasets: [
		{title: "Premaxillary-Maxillary Suture, WT and Fgfr2+/S252W (Apert syndrome mouse model), E16.5 and E18.5", species: "Mus musculus", assay_type: "RNA-seq"},
		{title: "Frontal suture, Fgfr2+/S252W (Apert syndrome mouse model), E16.5 and E18.5", species: "Mus musculus", assay_type: "RNA-seq"},
		{title: "Coronal Suture, WT, Fgfr2+/S252W (Apert syndrome mouse model), Twist1+/- (Saethre-Chotzen syndrome mouse model), E14.5", species: "Mus musculus", assay_type: "RNA-seq"},
		{title: "Interpalatine suture, WT and Fgfr2+/S252W (Apert syndrome mouse model), E16.5 and E18.5", species: "Mus musculus", assay_type: "RNA-seq"},
		{title: "Sagittal Suture, WT and Fgfr2+/S252W (Apert syndrome mouse model), E16.5 and E18.5", species: "Mus musculus", assay_type: "RNA-seq"},
	]
}

genes: "HAND2": {
	_in_facebase: true
	facebase_id:  "FB00001143"
	facebase_datasets: [
		{title: "Gene summary for Hand2", species: "Mus musculus", assay_type: "gene summary"},
	]
}

genes: "IRF6": {
	_in_facebase: true
	facebase_id:  "FB00001144"
	facebase_datasets: [
		{title: "Gene summary for IRF6", species: "Mus musculus", assay_type: "gene summary"},
	]
}

genes: "MSX1": {
	_in_facebase: true
	facebase_id:  "FB00000601.01"
	facebase_datasets: [
		{title: "microCT - Soft Tissue of a Msx1+/+ Control mouse at E16.5", species: "Mus musculus", assay_type: "microCT"},
		{title: "microCT - Bone Tissue of an Msx1-/- mouse at E16.5", species: "Mus musculus", assay_type: "microCT"},
		{title: "microCT - Bone Tissue of Msx1-/- mouse at P0", species: "Mus musculus", assay_type: "microCT"},
		{title: "microCT - Soft Tissue of Msx1-- Mice at E16.5", species: "Mus musculus", assay_type: "microCT"},
		{title: "microCT - Soft Tissue of Msx1-- Mouse at E15.5", species: "Mus musculus", assay_type: "microCT"},
	]
}

genes: "RUNX2": {
	_in_facebase: true
	facebase_id:  "FB00001363"
	facebase_datasets: [
		{title: "BRD4 binds to active cranial neural crest enhancers to regulate RUNX2 activity during osteoblast differentiation", species: "Mus musculus", assay_type: "enhancer assay"},
		{title: "Runx2 plays a critical role in tooth root development", species: "Mus musculus", assay_type: "other"},
		{title: "Gene summary for Runx2", species: "Mus musculus", assay_type: "gene summary"},
		{title: "Runx2-Twist1 interaction coordinates cranial neural crest guidance of soft palate myogenesis", species: "Mus musculus", assay_type: "other"},
		{title: "Runx2 regulates mouse tooth root development via activation of 1 WNT inhibitor Notum", species: "Mus musculus", assay_type: "other"},
	]
}

genes: "SHH": {
	_in_facebase: true
	facebase_id:  "FB00001209"
	facebase_datasets: [
		{title: "Shh: A standardized mouse morphology dataset for MusMorph", species: "Mus musculus", assay_type: "morphology"},
	]
}

genes: "SOX2": {
	_in_facebase: true
	facebase_id:  "FB00001152"
	facebase_datasets: [
		{title: "Gene summary for Sox2", species: "Mus musculus", assay_type: "gene summary"},
	]
}

genes: "SOX9": {
	_in_facebase: true
	facebase_id:  "FB00001018"
	facebase_datasets: [
		{title: "Activity of predicted human neural crest enhancer 1.35Mb upstream of SOX9 in transgenic mouse embryos.", species: "Mus musculus", assay_type: "enhancer assay"},
		{title: "Activity of predicted human neural crest enhancer 1.25Mb  upstream of SOX9 in E11.5 transgenic mouse embryo", species: "Mus musculus", assay_type: "enhancer assay"},
		{title: "Activity of human neural crest enhancer 1.45Mb upstream of SOX9 in transgenic mouse embryos – Tg(hg19_chr17:68668081-68671159::LacZ).", species: "Mus musculus", assay_type: "enhancer assay"},
		{title: "Gene summary for Sox9", species: "Mus musculus", assay_type: "gene summary"},
		{title: "Activity of human neural crest enhancer near SOX9 in transgenic mouse embryos – Tg(hg38_chr17:70869447-70870220::LacZ).", species: "Mus musculus", assay_type: "enhancer assay"},
	]
}

genes: "TBX1": {
	_in_facebase: true
	facebase_id:  "FB00001153"
	facebase_datasets: [
		{title: "Gene summary for Tbx1", species: "Mus musculus", assay_type: "gene summary"},
	]
}

genes: "TFAP2A": {
	_in_facebase: true
	facebase_id:  "FB00001180"
	facebase_datasets: [
		{title: "micro CT of Tfap2a;Tfap2b;Crect mutant and control mice", species: "Mus musculus", assay_type: "microCT"},
		{title: "micro CT of Tfap2a;Tfap2b;Wnt1-Cre mutant and control mice", species: "Mus musculus", assay_type: "microCT"},
	]
}

genes: "TFAP2B": {
	_in_facebase: true
	facebase_id:  "FB00001180"
	facebase_datasets: [
		{title: "micro CT of Tfap2a;Tfap2b;Crect mutant and control mice", species: "Mus musculus", assay_type: "microCT"},
		{title: "micro CT of Tfap2a;Tfap2b;Wnt1-Cre mutant and control mice", species: "Mus musculus", assay_type: "microCT"},
	]
}

genes: "TGFBR2": {
	_in_facebase: true
	facebase_id:  "FB00000306"
	facebase_datasets: [
		{title: "microMRI images of skulls of cleft Tgfbr2 mouse at E18.5", species: "Mus musculus", assay_type: "microMRI"},
		{title: "Gene summary for Tgfbr2", species: "Mus musculus", assay_type: "gene summary"},
		{title: "microCT - Bone Tissue of  Tgfbr2 Control mouse at E18.5", species: "Mus musculus", assay_type: "microCT"},
		{title: "microCT - Bone Tissue of Tgfbr2 control mice at E17.5", species: "Mus musculus", assay_type: "microCT"},
		{title: "microCT - Soft Tissue of Tgfbr2 control mouse at E16.5", species: "Mus musculus", assay_type: "microCT"},
	]
}

genes: "TWIST1": {
	_in_facebase: true
	facebase_id:  "FB00001380"
	facebase_datasets: [
		{title: "Regenerated coronal suture restored neurocognitive defects in a Twist1 craniosynostosis mouse model", species: "Mus musculus", assay_type: "RNA-seq"},
		{title: "Frontal suture, WT and Twist1+/- (Saethre-Chotzen syndrome mouse model), E16.5 and E18.5", species: "Mus musculus", assay_type: "RNA-seq"},
		{title: "Coronal Suture, WT, Fgfr2+/S252W (Apert syndrome mouse model), Twist1+/- (Saethre-Chotzen syndrome mouse model), E14.5", species: "Mus musculus", assay_type: "RNA-seq"},
		{title: "Runx2-Twist1 interaction coordinates cranial neural crest guidance of soft palate myogenesis", species: "Mus musculus", assay_type: "other"},
		{title: "Coronal suture, WT and Twist1+/- (Saethre-Chotzen syndrome mouse model), E18.5", species: "Mus musculus", assay_type: "RNA-seq"},
	]
}

genes: "WNT1": {
	_in_facebase: true
	facebase_id:  "FB00000320"
	facebase_datasets: [
		{title: "microCT - Bone Tissue of Wnt1-Cre;Tgbr2fl/fl;tgfb2+ mouse at E18.5", species: "Mus musculus", assay_type: "microCT"},
		{title: " microCT - Bone Tissue of Wnt1-Cre; Tgfbr2flfl  Mouse at E18.5", species: "Mus musculus", assay_type: "microCT"},
		{title: "MicroCT-Skull Wnt1-Cre;Alk5fl/fl mouse at P0", species: "Mus musculus", assay_type: "microCT"},
		{title: "Whole-genome transcriptome profiling of E12.5 Wnt1-Cre;Alk5flfl by microarray of maxilla and mandible", species: "Mus musculus", assay_type: "other"},
		{title: "Whole-genome transcriptome profiling of E14.5 Wnt1-Cre;Alk5flfl by microarray of maxilla and mandible", species: "Mus musculus", assay_type: "other"},
	]
}
