package froq

// gnomAD: gene constraint metrics for neural crest genes.
// Source: gnomAD GraphQL API (GRCh38)
// Generated by normalizers/from_gnomad.py -- 91 genes

genes: {
	"ADAM10": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000137845"
		pli_score:  1
		loeuf_score: 0.276
		oe_lof:     0.179
	}
	"ALDH1A2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000128918"
		pli_score:  0.165
		loeuf_score: 0.581
		oe_lof:     0.419
	}
	"AXIN2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000168646"
		pli_score:  1
		loeuf_score: 0.397
		oe_lof:     0.2757
	}
	"BMP2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000125845"
		pli_score:  1
		loeuf_score: 0.213
		oe_lof:     0.0676
	}
	"BMP4": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000125378"
		pli_score:  1
		loeuf_score: 0.258
		oe_lof:     0.09973
	}
	"BMP7": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000101144"
		pli_score:  0.9588
		loeuf_score: 0.523
		oe_lof:     0.3226
	}
	"CDH11": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000140937"
		pli_score:  1
		loeuf_score: 0.249
		oe_lof:     0.138
	}
	"CDH2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000170558"
		pli_score:  1
		loeuf_score: 0.336
		oe_lof:     0.2114
	}
	"CDH6": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000113361"
		pli_score:  0.9486
		loeuf_score: 0.511
		oe_lof:     0.3606
	}
	"CHD7": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000171316"
		pli_score:  1
		loeuf_score: 0.109
		oe_lof:     0.07557
	}
	"CTNNB1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000168036"
		pli_score:  1
		loeuf_score: 0.139
		oe_lof:     0.07022
	}
	"CXCR4": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000121966"
		pli_score:  0.9691
		loeuf_score: 0.514
		oe_lof:     0.2604
	}
	"DLL1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000198719"
		pli_score:  1
		loeuf_score: 0.236
		oe_lof:     0.1353
	}
	"DLX2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000115844"
		pli_score:  0.9577
		loeuf_score: 0.529
		oe_lof:     0.293
	}
	"DLX3": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000064195"
		pli_score:  0.9073
		loeuf_score: 0.559
		oe_lof:     0.3205
	}
	"DLX5": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000105880"
		pli_score:  0.9812
		loeuf_score: 0.498
		oe_lof:     0.2761
	}
	"DLX6": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000006377"
		pli_score:  0.9984
		loeuf_score: 0.379
		oe_lof:     0.1658
	}
	"ECE1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000117298"
		pli_score:  0.9876
		loeuf_score: 0.482
		oe_lof:     0.3638
	}
	"EDN1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000078401"
		pli_score:  0.004532
		loeuf_score: 0.84
		oe_lof:     0.5457
	}
	"EDN3": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000124205"
		pli_score:  0.3818
		loeuf_score: 0.696
		oe_lof:     0.3989
	}
	"EDNRA": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000151617"
		pli_score:  0.9991
		loeuf_score: 0.424
		oe_lof:     0.2502
	}
	"EDNRB": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000136160"
		pli_score:  0.4944
		loeuf_score: 0.585
		oe_lof:     0.3948
	}
	"ERBB3": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000065361"
		pli_score:  2.622e-16
		loeuf_score: 0.695
		oe_lof:     0.5853
	}
	"ETS1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000134954"
		pli_score:  0.9998
		loeuf_score: 0.393
		oe_lof:     0.2317
	}
	"EVC": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000072840"
		pli_score:  6.296e-37
		loeuf_score: 1.134
		oe_lof:     0.9688
	}
	"FGF8": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000107831"
		pli_score:  0.06074
		loeuf_score: 0.765
		oe_lof:     0.4721
	}
	"FGFR1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000077782"
		pli_score:  1
		loeuf_score: 0.274
		oe_lof:     0.1847
	}
	"FGFR2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000066468"
		pli_score:  1
		loeuf_score: 0.278
		oe_lof:     0.1874
	}
	"FGFR3": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000068078"
		pli_score:  0.9986
		loeuf_score: 0.458
		oe_lof:     0.326
	}
	"FN1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000115414"
		pli_score:  1
		loeuf_score: 0.404
		oe_lof:     0.3411
	}
	"FOXD3": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000187140"
		pli_score:  0.03402
		loeuf_score: 1.889
		oe_lof:     1.134
	}
	"GATA4": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000136574"
		pli_score:  0.9912
		loeuf_score: 0.468
		oe_lof:     0.2494
	}
	"GBX2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000168505"
		pli_score:  0.8779
		loeuf_score: 0.596
		oe_lof:     0.2834
	}
	"GDNF": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000168621"
		pli_score:  0.5975
		loeuf_score: 0.725
		oe_lof:     0.3446
	}
	"GFRA1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000151892"
		pli_score:  0.9977
		loeuf_score: 0.445
		oe_lof:     0.2623
	}
	"HAND1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000113196"
		pli_score:  0.01039
		loeuf_score: 1.188
		oe_lof:     0.6585
	}
	"HAND2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000164107"
		pli_score:  0.8867
		loeuf_score: 0.601
		oe_lof:     0.191
	}
	"IRF6": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000117595"
		pli_score:  1
		loeuf_score: 0.214
		oe_lof:     0.1018
	}
	"ITGB1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000150093"
		pli_score:  0.9998
		loeuf_score: 0.396
		oe_lof:     0.2337
	}
	"JAG1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000101384"
		pli_score:  1
		loeuf_score: 0.211
		oe_lof:     0.144
	}
	"KIT": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000157404"
		pli_score:  1
		loeuf_score: 0.24
		oe_lof:     0.1561
	}
	"LEF1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000138795"
		pli_score:  0.9964
		loeuf_score: 0.459
		oe_lof:     0.2771
	}
	"MEF2C": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000081189"
		pli_score:  1
		loeuf_score: 0.212
		oe_lof:     0.09251
	}
	"MITF": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000187098"
		pli_score:  0.992
		loeuf_score: 0.482
		oe_lof:     0.3175
	}
	"MMP2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000087245"
		pli_score:  6.476e-05
		loeuf_score: 0.654
		oe_lof:     0.5004
	}
	"MMP9": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000100985"
		pli_score:  3.922e-25
		loeuf_score: 1.208
		oe_lof:     0.9943
	}
	"MSX1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000163132"
		pli_score:  0.0006631
		loeuf_score: 1.289
		oe_lof:     0.7794
	}
	"MSX2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000120149"
		pli_score:  0.00934
		loeuf_score: 1.013
		oe_lof:     0.5973
	}
	"MYCN": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000134323"
		pli_score:  0.9997
		loeuf_score: 0.311
		oe_lof:     0.1203
	}
	"NF1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000196712"
		pli_score:  0.9995
		loeuf_score: 0.449
		oe_lof:     0.3832
	}
	"NGFR": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000064300"
		pli_score:  3.807e-09
		loeuf_score: 1.111
		oe_lof:     0.8187
	}
	"NKX2-5": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000183072"
		pli_score:  0.9995
		loeuf_score: 0.321
		oe_lof:     0.1242
	}
	"NOTCH1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000148400"
		pli_score:  1
		loeuf_score: 0.217
		oe_lof:     0.164
	}
	"NOTCH2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000134250"
		pli_score:  1
		loeuf_score: 0.151
		oe_lof:     0.1076
	}
	"NR2F1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000175745"
		pli_score:  1
		loeuf_score: 0.133
		oe_lof:     0.02794
	}
	"NR2F2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000185551"
		pli_score:  1
		loeuf_score: 0.197
		oe_lof:     0.06256
	}
	"NRP1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000099250"
		pli_score:  1
		loeuf_score: 0.408
		oe_lof:     0.3025
	}
	"PAX7": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000009709"
		pli_score:  0.9767
		loeuf_score: 0.504
		oe_lof:     0.3319
	}
	"PHOX2B": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000109132"
		pli_score:  0.9923
		loeuf_score: 0.349
		oe_lof:     0.07362
	}
	"PLXNA2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000076356"
		pli_score:  0.0004607
		loeuf_score: 0.525
		oe_lof:     0.4371
	}
	"PMEL": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000185664"
		pli_score:  6.479e-13
		loeuf_score: 0.965
		oe_lof:     0.7591
	}
	"RAC1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000136238"
		pli_score:  0.9995
		loeuf_score: 0.25
		oe_lof:     0.05262
	}
	"RARA": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000131759"
		pli_score:  1
		loeuf_score: 0.254
		oe_lof:     0.1209
	}
	"RET": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000165731"
		pli_score:  1
		loeuf_score: 0.24
		oe_lof:     0.1636
	}
	"RHOA": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000067560"
		pli_score:  0.9896
		loeuf_score: 0.433
		oe_lof:     0.1677
	}
	"RUNX2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000124813"
		pli_score:  1
		loeuf_score: 0.352
		oe_lof:     0.2076
	}
	"SEMA3A": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000075213"
		pli_score:  0.9988
		loeuf_score: 0.453
		oe_lof:     0.3086
	}
	"SEMA3C": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000075223"
		pli_score:  1.897e-05
		loeuf_score: 0.738
		oe_lof:     0.5491
	}
	"SHH": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000164690"
		pli_score:  0.9752
		loeuf_score: 0.493
		oe_lof:     0.2153
	}
	"SMAD1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000170365"
		pli_score:  1
		loeuf_score: 0.281
		oe_lof:     0.1336
	}
	"SNAI1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000124216"
		pli_score:  0.001922
		loeuf_score: 0.896
		oe_lof:     0.5818
	}
	"SNAI2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000019549"
		pli_score:  0.9996
		loeuf_score: 0.283
		oe_lof:     0.08999
	}
	"SOX10": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000100146"
		pli_score:  1
		loeuf_score: 0.248
		oe_lof:     0.09578
	}
	"SOX2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000181449"
		pli_score:  0.9993
		loeuf_score: 0.302
		oe_lof:     0.09579
	}
	"SOX5": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000134532"
		pli_score:  1
		loeuf_score: 0.204
		oe_lof:     0.113
	}
	"SOX8": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000005513"
		pli_score:  0.04326
		loeuf_score: 0.904
		oe_lof:     0.5179
	}
	"SOX9": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000125398"
		pli_score:  1
		loeuf_score: 0.154
		oe_lof:     0.04897
	}
	"TBX1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000184058"
		pli_score:  0.123
		loeuf_score: 0.703
		oe_lof:     0.4419
	}
	"TBX5": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000089225"
		pli_score:  1
		loeuf_score: 0.267
		oe_lof:     0.1481
	}
	"TCOF1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000070814"
		pli_score:  1
		loeuf_score: 0.288
		oe_lof:     0.2155
	}
	"TFAP2A": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000137203"
		pli_score:  0.9999
		loeuf_score: 0.334
		oe_lof:     0.1693
	}
	"TGFBR1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000106799"
		pli_score:  0.964
		loeuf_score: 0.509
		oe_lof:     0.35
	}
	"TGFBR2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000163513"
		pli_score:  0.9079
		loeuf_score: 0.531
		oe_lof:     0.3584
	}
	"TWIST1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000122691"
		pli_score:  0.006781
		loeuf_score: 1.451
		oe_lof:     0.7787
	}
	"TWIST2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000233608"
		pli_score:  0.7937
		loeuf_score: 0.714
		oe_lof:     0.1505
	}
	"TYR": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000077498"
		pli_score:  1.114e-21
		loeuf_score: 1.346
		oe_lof:     1.082
	}
	"TYRP1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000107165"
		pli_score:  3.998e-21
		loeuf_score: 1.398
		oe_lof:     1.117
	}
	"WNT1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000125084"
		pli_score:  0.002732
		loeuf_score: 0.957
		oe_lof:     0.6017
	}
	"WNT3A": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000154342"
		pli_score:  0.008071
		loeuf_score: 0.76
		oe_lof:     0.5067
	}
	"ZEB2": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000169554"
		pli_score:  1
		loeuf_score: 0.114
		oe_lof:     0.05762
	}
	"ZIC1": {
		_in_gnomad: true
		gnomad_id:  "ENSG00000152977"
		pli_score:  0.9999
		loeuf_score: 0.306
		oe_lof:     0.1338
	}
}
