package froq

// GTEx: tissue expression data for neural crest genes.
// Source: GTEx Portal API v2 + MyGene.info (Ensembl ID resolution)
// Generated by normalizers/from_gtex.py -- 95 genes

genes: {
	"ADAM10": {
		_in_gtex:  true
		gtex_id:   "ENSG00000137845"
		craniofacial_expression: 0.0
	}
	"ALDH1A2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000128918"
		craniofacial_expression: 0.0
	}
	"AXIN2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000168646"
		craniofacial_expression: 0.0
	}
	"BMP2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000125845"
		craniofacial_expression: 0.0
	}
	"BMP4": {
		_in_gtex:  true
		gtex_id:   "ENSG00000125378"
		craniofacial_expression: 0.0
	}
	"BMP7": {
		_in_gtex:  true
		gtex_id:   "ENSG00000101144"
		craniofacial_expression: 0.0
	}
	"CDH11": {
		_in_gtex:  true
		gtex_id:   "ENSG00000140937"
		craniofacial_expression: 0.0
	}
	"CDH2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000170558"
		craniofacial_expression: 0.0
	}
	"CDH6": {
		_in_gtex:  true
		gtex_id:   "ENSG00000113361"
		craniofacial_expression: 0.0
	}
	"CHD7": {
		_in_gtex:  true
		gtex_id:   "ENSG00000171316"
		craniofacial_expression: 0.0
	}
	"CTNNB1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000168036"
		craniofacial_expression: 0.0
	}
	"CXCR4": {
		_in_gtex:  true
		gtex_id:   "ENSG00000121966"
		craniofacial_expression: 0.0
	}
	"DCT": {
		_in_gtex:  true
		gtex_id:   "ENSG00000080166"
		craniofacial_expression: 0.0
	}
	"DLL1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000275555"
		craniofacial_expression: 0.0
	}
	"DLX2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000115844"
		craniofacial_expression: 0.0
	}
	"DLX3": {
		_in_gtex:  true
		gtex_id:   "ENSG00000064195"
		craniofacial_expression: 0.0
	}
	"DLX5": {
		_in_gtex:  true
		gtex_id:   "ENSG00000105880"
		craniofacial_expression: 0.0
	}
	"DLX6": {
		_in_gtex:  true
		gtex_id:   "ENSG00000006377"
		craniofacial_expression: 0.0
	}
	"ECE1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000117298"
		craniofacial_expression: 0.0
	}
	"EDN1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000078401"
		craniofacial_expression: 0.0
	}
	"EDN3": {
		_in_gtex:  true
		gtex_id:   "ENSG00000124205"
		craniofacial_expression: 0.0
	}
	"EDNRA": {
		_in_gtex:  true
		gtex_id:   "ENSG00000151617"
		craniofacial_expression: 0.0
	}
	"EDNRB": {
		_in_gtex:  true
		gtex_id:   "ENSG00000136160"
		craniofacial_expression: 0.0
	}
	"ERBB3": {
		_in_gtex:  true
		gtex_id:   "ENSG00000065361"
		craniofacial_expression: 0.0
	}
	"ETS1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000134954"
		craniofacial_expression: 0.0
	}
	"EVC": {
		_in_gtex:  true
		gtex_id:   "ENSG00000072840"
		craniofacial_expression: 0.0
	}
	"FGF8": {
		_in_gtex:  true
		gtex_id:   "ENSG00000107831"
		craniofacial_expression: 0.0
	}
	"FGFR1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000077782"
		craniofacial_expression: 0.0
	}
	"FGFR2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000066468"
		craniofacial_expression: 0.0
	}
	"FGFR3": {
		_in_gtex:  true
		gtex_id:   "ENSG00000068078"
		craniofacial_expression: 0.0
	}
	"FN1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000115414"
		craniofacial_expression: 0.0
	}
	"FOXD3": {
		_in_gtex:  true
		gtex_id:   "ENSG00000187140"
		craniofacial_expression: 0.0
	}
	"GATA4": {
		_in_gtex:  true
		gtex_id:   "ENSG00000285109"
		craniofacial_expression: 0.0
	}
	"GBX2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000168505"
		craniofacial_expression: 0.0
	}
	"GDNF": {
		_in_gtex:  true
		gtex_id:   "ENSG00000168621"
		craniofacial_expression: 0.0
	}
	"GFRA1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000151892"
		craniofacial_expression: 0.0
	}
	"HAND1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000113196"
		craniofacial_expression: 0.0
	}
	"HAND2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000164107"
		craniofacial_expression: 0.0
	}
	"IRF6": {
		_in_gtex:  true
		gtex_id:   "ENSG00000117595"
		craniofacial_expression: 0.0
	}
	"ITGB1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000150093"
		craniofacial_expression: 0.0
	}
	"JAG1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000101384"
		craniofacial_expression: 0.0
	}
	"KIT": {
		_in_gtex:  true
		gtex_id:   "ENSG00000157404"
		craniofacial_expression: 0.0
	}
	"LEF1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000138795"
		craniofacial_expression: 0.0
	}
	"MEF2C": {
		_in_gtex:  true
		gtex_id:   "ENSG00000081189"
		craniofacial_expression: 0.0
	}
	"MITF": {
		_in_gtex:  true
		gtex_id:   "ENSG00000187098"
		craniofacial_expression: 0.0
	}
	"MMP2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000087245"
		craniofacial_expression: 0.0
	}
	"MMP9": {
		_in_gtex:  true
		gtex_id:   "ENSG00000100985"
		craniofacial_expression: 0.0
	}
	"MSX1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000163132"
		craniofacial_expression: 0.0
	}
	"MSX2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000120149"
		craniofacial_expression: 0.0
	}
	"MYCN": {
		_in_gtex:  true
		gtex_id:   "ENSG00000134323"
		craniofacial_expression: 0.0
	}
	"NF1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000196712"
		craniofacial_expression: 0.0
	}
	"NGFR": {
		_in_gtex:  true
		gtex_id:   "ENSG00000064300"
		craniofacial_expression: 0.0
	}
	"NKX2-5": {
		_in_gtex:  true
		gtex_id:   "ENSG00000183072"
		craniofacial_expression: 0.0
	}
	"NOTCH1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000148400"
		craniofacial_expression: 0.0
	}
	"NOTCH2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000134250"
		craniofacial_expression: 0.0
	}
	"NR2F1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000175745"
		craniofacial_expression: 0.0
	}
	"NR2F2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000185551"
		craniofacial_expression: 0.0
	}
	"NRP1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000099250"
		craniofacial_expression: 0.0
	}
	"PAX3": {
		_in_gtex:  true
		gtex_id:   "ENSG00000135903"
		craniofacial_expression: 0.0
	}
	"PAX6": {
		_in_gtex:  true
		gtex_id:   "ENSG00000007372"
		craniofacial_expression: 0.0
	}
	"PAX7": {
		_in_gtex:  true
		gtex_id:   "ENSG00000009709"
		craniofacial_expression: 0.0
	}
	"PHOX2B": {
		_in_gtex:  true
		gtex_id:   "ENSG00000109132"
		craniofacial_expression: 0.0
	}
	"PLXNA2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000076356"
		craniofacial_expression: 0.0
	}
	"PMEL": {
		_in_gtex:  true
		gtex_id:   "ENSG00000185664"
		craniofacial_expression: 0.0
	}
	"RAC1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000136238"
		craniofacial_expression: 0.0
	}
	"RARA": {
		_in_gtex:  true
		gtex_id:   "ENSG00000131759"
		craniofacial_expression: 0.0
	}
	"RET": {
		_in_gtex:  true
		gtex_id:   "ENSG00000165731"
		craniofacial_expression: 0.0
	}
	"RHOA": {
		_in_gtex:  true
		gtex_id:   "ENSG00000067560"
		craniofacial_expression: 0.0
	}
	"RUNX2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000124813"
		craniofacial_expression: 0.0
	}
	"SEMA3A": {
		_in_gtex:  true
		gtex_id:   "ENSG00000075213"
		craniofacial_expression: 0.0
	}
	"SEMA3C": {
		_in_gtex:  true
		gtex_id:   "ENSG00000075223"
		craniofacial_expression: 0.0
	}
	"SHH": {
		_in_gtex:  true
		gtex_id:   "ENSG00000164690"
		craniofacial_expression: 0.0
	}
	"SMAD1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000170365"
		craniofacial_expression: 0.0
	}
	"SNAI1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000124216"
		craniofacial_expression: 0.0
	}
	"SNAI2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000019549"
		craniofacial_expression: 0.0
	}
	"SOX10": {
		_in_gtex:  true
		gtex_id:   "ENSG00000100146"
		craniofacial_expression: 0.0
	}
	"SOX2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000181449"
		craniofacial_expression: 0.0
	}
	"SOX5": {
		_in_gtex:  true
		gtex_id:   "ENSG00000134532"
		craniofacial_expression: 0.0
	}
	"SOX8": {
		_in_gtex:  true
		gtex_id:   "ENSG00000005513"
		craniofacial_expression: 0.0
	}
	"SOX9": {
		_in_gtex:  true
		gtex_id:   "ENSG00000125398"
		craniofacial_expression: 0.0
	}
	"TBX1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000184058"
		craniofacial_expression: 0.0
	}
	"TBX5": {
		_in_gtex:  true
		gtex_id:   "ENSG00000089225"
		craniofacial_expression: 0.0
	}
	"TCOF1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000070814"
		craniofacial_expression: 0.0
	}
	"TFAP2A": {
		_in_gtex:  true
		gtex_id:   "ENSG00000137203"
		craniofacial_expression: 0.0
	}
	"TFAP2B": {
		_in_gtex:  true
		gtex_id:   "ENSG00000008196"
		craniofacial_expression: 0.0
	}
	"TGFBR1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000106799"
		craniofacial_expression: 0.0
	}
	"TGFBR2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000163513"
		craniofacial_expression: 0.0
	}
	"TWIST1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000122691"
		craniofacial_expression: 0.0
	}
	"TWIST2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000288335"
		craniofacial_expression: 0.0
	}
	"TYR": {
		_in_gtex:  true
		gtex_id:   "ENSG00000077498"
		craniofacial_expression: 0.0
	}
	"TYRP1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000107165"
		craniofacial_expression: 0.0
	}
	"WNT1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000125084"
		craniofacial_expression: 0.0
	}
	"WNT3A": {
		_in_gtex:  true
		gtex_id:   "ENSG00000154342"
		craniofacial_expression: 0.0
	}
	"ZEB2": {
		_in_gtex:  true
		gtex_id:   "ENSG00000169554"
		craniofacial_expression: 0.0
	}
	"ZIC1": {
		_in_gtex:  true
		gtex_id:   "ENSG00000152977"
		craniofacial_expression: 0.0
	}
}
