package lacuene

// OMIM: Mendelian disease associations for neural crest genes.
// Source: data/omim/omim_subset.json (bundled subset, hand-curated from omim.org)
// Generated by normalizers/from_omim.py — 95 genes

genes: {
	"ADAM10": {
		_in_omim: true
		omim_id:  "602192"
		omim_title: "A disintegrin and metalloproteinase domain 10"
		omim_syndromes: ["Reticulate acropigmentation of Kitamura, 615537"]
		inheritance: "AD"
	}
	"ALDH1A2": {
		_in_omim: true
		omim_id:  "603687"
		omim_title: "Aldehyde dehydrogenase 1 family, member A2"
	}
	"AXIN2": {
		_in_omim: true
		omim_id:  "604025"
		omim_title: "Axis inhibitor 2"
		omim_syndromes: ["Oligodontia-colorectal cancer syndrome, 608615"]
		inheritance: "AD"
	}
	"BMP2": {
		_in_omim: true
		omim_id:  "112261"
		omim_title: "Bone morphogenetic protein 2"
		omim_syndromes: ["Short stature, facial dysmorphism, and skeletal anomalies with or without cardiac anomalies 1, 617877"]
		inheritance: "AD"
	}
	"BMP4": {
		_in_omim: true
		omim_id:  "112262"
		omim_title: "Bone morphogenetic protein 4"
		omim_syndromes: ["Microphthalmia, syndromic 6, 607932"]
		inheritance: "AD"
	}
	"BMP7": {
		_in_omim: true
		omim_id:  "112267"
		omim_title: "Bone morphogenetic protein 7"
	}
	"CDH11": {
		_in_omim: true
		omim_id:  "600023"
		omim_title: "Cadherin 11"
		omim_syndromes: ["Elsahy-Waters syndrome, 211380"]
		inheritance: "AR"
	}
	"CDH2": {
		_in_omim: true
		omim_id:  "114020"
		omim_title: "Cadherin 2"
		omim_syndromes: [
			"Arrhythmogenic right ventricular dysplasia 14, 618920",
			"Agenesis of corpus callosum, cardiac, ocular, and genital syndrome, 618929",
		]
		inheritance: "AD"
	}
	"CDH6": {
		_in_omim: true
		omim_id:  "603007"
		omim_title: "Cadherin 6"
	}
	"CHD7": {
		_in_omim: true
		omim_id:  "608892"
		omim_title: "Chromodomain helicase DNA binding protein 7"
		omim_syndromes: ["CHARGE syndrome, 214800"]
		inheritance: "AD"
	}
	"CTNNB1": {
		_in_omim: true
		omim_id:  "116806"
		omim_title: "Catenin, beta-1"
		omim_syndromes: [
			"Neurodevelopmental disorder with spastic diplegia and visual defects, 615075",
			"Exudative vitreoretinopathy 7, 617572",
		]
		inheritance: "AD"
	}
	"CXCR4": {
		_in_omim: true
		omim_id:  "162643"
		omim_title: "Chemokine, CXC motif, receptor 4"
		omim_syndromes: ["WHIM syndrome 1, 193670"]
		inheritance: "AD"
	}
	"DCT": {
		_in_omim: true
		omim_id:  "191275"
		omim_title: "Dopachrome tautomerase"
		omim_syndromes: ["Oculocutaneous albinism, type VIII, 619165"]
		inheritance: "AR"
	}
	"DLL1": {
		_in_omim: true
		omim_id:  "606582"
		omim_title: "Delta-like canonical Notch ligand 1"
		omim_syndromes: ["Neurodevelopmental disorder with nonspecific brain abnormalities and with or without seizures, 618709"]
		inheritance: "AD"
	}
	"DLX2": {
		_in_omim: true
		omim_id:  "126255"
		omim_title: "Distal-less homeobox 2"
	}
	"DLX3": {
		_in_omim: true
		omim_id:  "600525"
		omim_title: "Distal-less homeobox 3"
		omim_syndromes: ["Trichodentoosseous syndrome, 190320"]
		inheritance: "AD"
	}
	"DLX5": {
		_in_omim: true
		omim_id:  "600028"
		omim_title: "Distal-less homeobox 5"
		omim_syndromes: ["Split-hand/foot malformation 1 with sensorineural hearing loss, 220600"]
		inheritance: "AR"
	}
	"DLX6": {
		_in_omim: true
		omim_id:  "600030"
		omim_title: "Distal-less homeobox 6"
		omim_syndromes: ["Split-hand/foot malformation 1, 183600"]
		inheritance: "AD"
	}
	"ECE1": {
		_in_omim: true
		omim_id:  "600423"
		omim_title: "Endothelin-converting enzyme 1"
		omim_syndromes: ["Hirschsprung disease, cardiac defects, and autonomic dysfunction, 613870"]
		inheritance: "AD"
	}
	"EDN1": {
		_in_omim: true
		omim_id:  "131240"
		omim_title: "Endothelin 1"
		omim_syndromes: ["Auriculocondylar syndrome 3, 615706"]
		inheritance: "AR"
	}
	"EDN3": {
		_in_omim: true
		omim_id:  "131242"
		omim_title: "Endothelin 3"
		omim_syndromes: [
			"Waardenburg syndrome, type 4B, 613265",
			"Hirschsprung disease, susceptibility to, 4, 613712",
		]
		inheritance: "AD/AR"
	}
	"EDNRA": {
		_in_omim: true
		omim_id:  "131243"
		omim_title: "Endothelin receptor, type A"
		omim_syndromes: ["Mandibulofacial dysostosis with alopecia, 616367"]
		inheritance: "AD"
	}
	"EDNRB": {
		_in_omim: true
		omim_id:  "131244"
		omim_title: "Endothelin receptor, type B"
		omim_syndromes: [
			"Waardenburg syndrome, type 4A, 277580",
			"Hirschsprung disease, susceptibility to, 2, 600155",
		]
		inheritance: "AD/AR"
	}
	"ERBB3": {
		_in_omim: true
		omim_id:  "190151"
		omim_title: "Erb-b2 receptor tyrosine kinase 3"
		omim_syndromes: ["Lethal congenital contracture syndrome 2, 607598"]
		inheritance: "AR"
	}
	"ETS1": {
		_in_omim: true
		omim_id:  "164720"
		omim_title: "ETS protooncogene 1, transcription factor"
		omim_syndromes: ["Jacobsen syndrome, 147791"]
		inheritance: "AD"
	}
	"EVC": {
		_in_omim: true
		omim_id:  "604831"
		omim_title: "EvC ciliary complex subunit 1"
		omim_syndromes: ["Ellis-van Creveld syndrome, 225500"]
		inheritance: "AR"
	}
	"FGF8": {
		_in_omim: true
		omim_id:  "600483"
		omim_title: "Fibroblast growth factor 8"
		omim_syndromes: ["Hypogonadotropic hypogonadism 6 with or without anosmia, 612702"]
		inheritance: "AD"
	}
	"FGFR1": {
		_in_omim: true
		omim_id:  "136350"
		omim_title: "Fibroblast growth factor receptor 1"
		omim_syndromes: [
			"Pfeiffer syndrome, 101600",
			"Hypogonadotropic hypogonadism 2 with or without anosmia, 147950",
			"Hartsfield syndrome, 615465",
			"Osteoglophonic dysplasia, 166250",
		]
		inheritance: "AD"
	}
	"FGFR2": {
		_in_omim: true
		omim_id:  "176943"
		omim_title: "Fibroblast growth factor receptor 2"
		omim_syndromes: [
			"Crouzon syndrome, 123500",
			"Apert syndrome, 101200",
			"Pfeiffer syndrome, 101600",
		]
		inheritance: "AD"
	}
	"FGFR3": {
		_in_omim: true
		omim_id:  "134934"
		omim_title: "Fibroblast growth factor receptor 3"
		omim_syndromes: [
			"Achondroplasia, 100800",
			"Thanatophoric dysplasia, type I, 187600",
			"Thanatophoric dysplasia, type II, 187601",
			"Muenke syndrome, 602849",
			"Hypochondroplasia, 146000",
		]
		inheritance: "AD"
	}
	"FN1": {
		_in_omim: true
		omim_id:  "135600"
		omim_title: "Fibronectin 1"
		omim_syndromes: [
			"Glomerulopathy with fibronectin deposits 2, 601894",
			"Spondylometaphyseal dysplasia, corner fracture type, 184255",
		]
		inheritance: "AD"
	}
	"FOXD3": {
		_in_omim: true
		omim_id:  "611539"
		omim_title: "Forkhead box D3"
	}
	"GATA4": {
		_in_omim: true
		omim_id:  "600576"
		omim_title: "GATA-binding protein 4"
		omim_syndromes: [
			"Atrial septal defect 2, 607941",
			"Ventricular septal defect 1, 614429",
			"Atrioventricular septal defect 4, 614430",
		]
		inheritance: "AD"
	}
	"GBX2": {
		_in_omim: true
		omim_id:  "601135"
		omim_title: "Gastrulation brain homeobox 2"
	}
	"GDNF": {
		_in_omim: true
		omim_id:  "600837"
		omim_title: "Glial cell line-derived neurotrophic factor"
		omim_syndromes: ["Hirschsprung disease, susceptibility to, 3, 613711"]
		inheritance: "AD"
	}
	"GFRA1": {
		_in_omim: true
		omim_id:  "601496"
		omim_title: "GDNF family receptor alpha-1"
	}
	"HAND1": {
		_in_omim: true
		omim_id:  "602406"
		omim_title: "Heart- and neural crest derivatives-expressed 1"
	}
	"HAND2": {
		_in_omim: true
		omim_id:  "602407"
		omim_title: "Heart- and neural crest derivatives-expressed 2"
	}
	"IRF6": {
		_in_omim: true
		omim_id:  "607199"
		omim_title: "Interferon regulatory factor 6"
		omim_syndromes: [
			"Van der Woude syndrome, 119300",
			"Popliteal pterygium syndrome, 119500",
		]
		inheritance: "AD"
	}
	"ITGB1": {
		_in_omim: true
		omim_id:  "135630"
		omim_title: "Integrin subunit beta-1"
	}
	"JAG1": {
		_in_omim: true
		omim_id:  "601920"
		omim_title: "Jagged 1"
		omim_syndromes: [
			"Alagille syndrome 1, 118450",
			"Tetralogy of Fallot, 187500",
		]
		inheritance: "AD"
	}
	"KIT": {
		_in_omim: true
		omim_id:  "164920"
		omim_title: "KIT protooncogene, receptor tyrosine kinase"
		omim_syndromes: [
			"Piebaldism, 172800",
			"Gastrointestinal stromal tumor, 606764",
		]
		inheritance: "AD"
	}
	"LEF1": {
		_in_omim: true
		omim_id:  "153245"
		omim_title: "Lymphoid enhancer-binding factor 1"
	}
	"MEF2C": {
		_in_omim: true
		omim_id:  "600662"
		omim_title: "Myocyte enhancer factor 2C"
		omim_syndromes: ["Neurodevelopmental disorder with hypotonia, stereotypic hand movements, and impaired language, 613443"]
		inheritance: "AD"
	}
	"MITF": {
		_in_omim: true
		omim_id:  "156845"
		omim_title: "Microphthalmia-associated transcription factor"
		omim_syndromes: [
			"Waardenburg syndrome, type 2A, 193510",
			"Tietz albinism-deafness syndrome, 103500",
		]
		inheritance: "AD"
	}
	"MMP2": {
		_in_omim: true
		omim_id:  "120360"
		omim_title: "Matrix metalloproteinase 2"
		omim_syndromes: ["Multicentric osteolysis, nodulosis, and arthropathy, 259600"]
		inheritance: "AR"
	}
	"MMP9": {
		_in_omim: true
		omim_id:  "120361"
		omim_title: "Matrix metalloproteinase 9"
		omim_syndromes: ["Metaphyseal anadysplasia 2, 613073"]
		inheritance: "AR"
	}
	"MSX1": {
		_in_omim: true
		omim_id:  "142983"
		omim_title: "Muscle segment homeobox 1"
		omim_syndromes: [
			"Tooth agenesis, selective, 1, 106600",
			"Orofacial cleft 5, 608874",
		]
		inheritance: "AD"
	}
	"MSX2": {
		_in_omim: true
		omim_id:  "123101"
		omim_title: "Muscle segment homeobox 2"
		omim_syndromes: [
			"Craniosynostosis, type 2, 604757",
			"Parietal foramina 1, 168500",
		]
		inheritance: "AD"
	}
	"MYCN": {
		_in_omim: true
		omim_id:  "164840"
		omim_title: "MYCN protooncogene, bHLH transcription factor"
		omim_syndromes: ["Feingold syndrome 1, 164280"]
		inheritance: "AD"
	}
	"NF1": {
		_in_omim: true
		omim_id:  "613113"
		omim_title: "Neurofibromin 1"
		omim_syndromes: [
			"Neurofibromatosis, type I, 162200",
			"Neurofibromatosis-Noonan syndrome, 601321",
		]
		inheritance: "AD"
	}
	"NGFR": {
		_in_omim: true
		omim_id:  "162010"
		omim_title: "Nerve growth factor receptor"
	}
	"NKX2-5": {
		_in_omim: true
		omim_id:  "600584"
		omim_title: "NK2 homeobox 5"
		omim_syndromes: [
			"Atrial septal defect 7 with or without atrioventricular conduction defects, 108900",
			"Tetralogy of Fallot, 187500",
			"Ventricular septal defect 3, 614432",
		]
		inheritance: "AD"
	}
	"NOTCH1": {
		_in_omim: true
		omim_id:  "190198"
		omim_title: "Notch receptor 1"
		omim_syndromes: [
			"Aortic valve disease 1, 109730",
			"Adams-Oliver syndrome 5, 616028",
		]
		inheritance: "AD"
	}
	"NOTCH2": {
		_in_omim: true
		omim_id:  "600275"
		omim_title: "Notch receptor 2"
		omim_syndromes: [
			"Alagille syndrome 2, 610205",
			"Hajdu-Cheney syndrome, 102500",
		]
		inheritance: "AD"
	}
	"NR2F1": {
		_in_omim: true
		omim_id:  "132890"
		omim_title: "Nuclear receptor subfamily 2, group F, member 1"
		omim_syndromes: ["Bosch-Boonstra-Schaaf optic atrophy syndrome, 615722"]
		inheritance: "AD"
	}
	"NR2F2": {
		_in_omim: true
		omim_id:  "107773"
		omim_title: "Nuclear receptor subfamily 2, group F, member 2"
		omim_syndromes: ["Congenital heart defects, multiple types, 4, 615779"]
		inheritance: "AD"
	}
	"NRP1": {
		_in_omim: true
		omim_id:  "602069"
		omim_title: "Neuropilin 1"
	}
	"PAX3": {
		_in_omim: true
		omim_id:  "606597"
		omim_title: "Paired box gene 3"
		omim_syndromes: [
			"Waardenburg syndrome, type 1, 193500",
			"Waardenburg syndrome, type 3, 148820",
		]
		inheritance: "AD"
	}
	"PAX6": {
		_in_omim: true
		omim_id:  "607108"
		omim_title: "Paired box gene 6"
		omim_syndromes: [
			"Aniridia 1, 106210",
			"Anterior segment dysgenesis 5, 604229",
		]
		inheritance: "AD"
	}
	"PAX7": {
		_in_omim: true
		omim_id:  "167410"
		omim_title: "Paired box gene 7"
		omim_syndromes: ["Rhabdomyosarcoma 2, alveolar, 268220"]
		inheritance: "AD"
	}
	"PHOX2B": {
		_in_omim: true
		omim_id:  "603851"
		omim_title: "Paired-like homeobox 2B"
		omim_syndromes: ["Central hypoventilation syndrome, congenital, 1, 209880"]
		inheritance: "AD"
	}
	"PLXNA2": {
		_in_omim: true
		omim_id:  "601054"
		omim_title: "Plexin A2"
	}
	"PMEL": {
		_in_omim: true
		omim_id:  "155550"
		omim_title: "Premelanosome protein"
	}
	"RAC1": {
		_in_omim: true
		omim_id:  "602048"
		omim_title: "Ras-related C3 botulinum toxin substrate 1"
		omim_syndromes: ["Intellectual developmental disorder, autosomal dominant 48, 617751"]
		inheritance: "AD"
	}
	"RARA": {
		_in_omim: true
		omim_id:  "180240"
		omim_title: "Retinoic acid receptor, alpha"
	}
	"RET": {
		_in_omim: true
		omim_id:  "164761"
		omim_title: "RET protooncogene"
		omim_syndromes: [
			"Hirschsprung disease, susceptibility to, 1, 142623",
			"Multiple endocrine neoplasia, type IIA, 171400",
			"Multiple endocrine neoplasia, type IIB, 162300",
			"Medullary thyroid carcinoma, 155240",
		]
		inheritance: "AD"
	}
	"RHOA": {
		_in_omim: true
		omim_id:  "165390"
		omim_title: "Ras homolog gene family, member A"
		omim_syndromes: ["Ectodermal dysplasia with facial dysmorphism and acral, ocular, and brain anomalies, 618727"]
		inheritance: "AD"
	}
	"RUNX2": {
		_in_omim: true
		omim_id:  "600211"
		omim_title: "RUNX family transcription factor 2"
		omim_syndromes: ["Cleidocranial dysplasia, 119600"]
		inheritance: "AD"
	}
	"SEMA3A": {
		_in_omim: true
		omim_id:  "603961"
		omim_title: "Semaphorin 3A"
	}
	"SEMA3C": {
		_in_omim: true
		omim_id:  "602645"
		omim_title: "Semaphorin 3C"
	}
	"SHH": {
		_in_omim: true
		omim_id:  "600725"
		omim_title: "Sonic hedgehog signaling molecule"
		omim_syndromes: ["Holoprosencephaly 3, 142945"]
		inheritance: "AD"
	}
	"SMAD1": {
		_in_omim: true
		omim_id:  "601595"
		omim_title: "SMAD family member 1"
	}
	"SNAI1": {
		_in_omim: true
		omim_id:  "604238"
		omim_title: "Snail family transcriptional repressor 1"
	}
	"SNAI2": {
		_in_omim: true
		omim_id:  "602150"
		omim_title: "Snail family transcriptional repressor 2"
		omim_syndromes: [
			"Piebaldism, 172800",
			"Waardenburg syndrome, type 2D, 608890",
		]
		inheritance: "AR"
	}
	"SOX10": {
		_in_omim: true
		omim_id:  "602229"
		omim_title: "SRY-box transcription factor 10"
		omim_syndromes: [
			"Waardenburg syndrome, type 4C, 613266",
			"PCWH syndrome, 609136",
		]
		inheritance: "AD"
	}
	"SOX2": {
		_in_omim: true
		omim_id:  "184429"
		omim_title: "SRY-box 2"
		omim_syndromes: ["Microphthalmia, syndromic 3, 206900"]
		inheritance: "AD"
	}
	"SOX5": {
		_in_omim: true
		omim_id:  "604975"
		omim_title: "SRY-box 5"
		omim_syndromes: ["Lamb-Shaffer syndrome, 616803"]
		inheritance: "AD"
	}
	"SOX8": {
		_in_omim: true
		omim_id:  "605923"
		omim_title: "SRY-box 8"
	}
	"SOX9": {
		_in_omim: true
		omim_id:  "608160"
		omim_title: "SRY-box transcription factor 9"
		omim_syndromes: ["Campomelic dysplasia, 114290"]
		inheritance: "AD"
	}
	"TBX1": {
		_in_omim: true
		omim_id:  "602054"
		omim_title: "T-box transcription factor 1"
		omim_syndromes: [
			"DiGeorge syndrome, 188400",
			"Velocardiofacial syndrome, 192430",
		]
		inheritance: "AD"
	}
	"TBX5": {
		_in_omim: true
		omim_id:  "601620"
		omim_title: "T-box transcription factor 5"
		omim_syndromes: ["Holt-Oram syndrome, 142900"]
		inheritance: "AD"
	}
	"TCOF1": {
		_in_omim: true
		omim_id:  "606847"
		omim_title: "Treacle ribosome biogenesis factor 1"
		omim_syndromes: ["Treacher Collins syndrome 1, 154500"]
		inheritance: "AD"
	}
	"TFAP2A": {
		_in_omim: true
		omim_id:  "107580"
		omim_title: "Transcription factor AP-2 alpha"
		omim_syndromes: ["Branchiooculofacial syndrome, 113620"]
		inheritance: "AD"
	}
	"TFAP2B": {
		_in_omim: true
		omim_id:  "601601"
		omim_title: "Transcription factor AP-2 beta"
		omim_syndromes: ["Char syndrome, 169100"]
		inheritance: "AD"
	}
	"TGFBR1": {
		_in_omim: true
		omim_id:  "190181"
		omim_title: "Transforming growth factor-beta receptor, type I"
		omim_syndromes: ["Loeys-Dietz syndrome 1, 609192"]
		inheritance: "AD"
	}
	"TGFBR2": {
		_in_omim: true
		omim_id:  "190182"
		omim_title: "Transforming growth factor-beta receptor, type II"
		omim_syndromes: ["Loeys-Dietz syndrome 2, 610168"]
		inheritance: "AD"
	}
	"TWIST1": {
		_in_omim: true
		omim_id:  "601622"
		omim_title: "Twist family bHLH transcription factor 1"
		omim_syndromes: ["Saethre-Chotzen syndrome, 101400"]
		inheritance: "AD"
	}
	"TWIST2": {
		_in_omim: true
		omim_id:  "607556"
		omim_title: "Twist family bHLH transcription factor 2"
		omim_syndromes: [
			"Focal facial dermal dysplasia 3, Setleis type, 227260",
			"Ablepharon-macrostomia syndrome, 200110",
			"Barber-Say syndrome, 209885",
		]
		inheritance: "AD/AR"
	}
	"TYR": {
		_in_omim: true
		omim_id:  "606933"
		omim_title: "Tyrosinase"
		omim_syndromes: [
			"Albinism, oculocutaneous, type IA, 203100",
			"Albinism, oculocutaneous, type IB, 606952",
		]
		inheritance: "AR"
	}
	"TYRP1": {
		_in_omim: true
		omim_id:  "115501"
		omim_title: "Tyrosinase-related protein 1"
		omim_syndromes: ["Albinism, oculocutaneous, type III, 203290"]
		inheritance: "AR"
	}
	"WNT1": {
		_in_omim: true
		omim_id:  "164820"
		omim_title: "Wingless-type MMTV integration site family, member 1"
		omim_syndromes: ["Osteogenesis imperfecta, type XV, 615220"]
		inheritance: "AR"
	}
	"WNT3A": {
		_in_omim: true
		omim_id:  "606359"
		omim_title: "Wingless-type MMTV integration site family, member 3A"
	}
	"ZEB2": {
		_in_omim: true
		omim_id:  "605802"
		omim_title: "Zinc finger E-box binding homeobox 2"
		omim_syndromes: ["Mowat-Wilson syndrome, 235730"]
		inheritance: "AD"
	}
	"ZIC1": {
		_in_omim: true
		omim_id:  "600470"
		omim_title: "Zinc finger protein of the cerebellum 1"
		omim_syndromes: ["Craniosynostosis 6, 616602"]
		inheritance: "AD"
	}
}
