package lacuene

// PubMed: craniofacial publication data for neural crest genes.
// Source: NCBI PubMed via E-utilities (esearch + esummary)
// Generated by normalizers/from_pubmed.py -- 95 genes

genes: {
	"ADAM10": {
		_in_pubmed:     true
		pubmed_gene_id: "102"
		pubmed_total:   33
		pubmed_recent:  9
	}
	"ALDH1A2": {
		_in_pubmed:     true
		pubmed_gene_id: "8854"
		pubmed_total:   14
		pubmed_recent:  6
		pubmed_papers: [
			{
				title: "Multiple roles for retinoid signaling in craniofacial development."
				pmid:  "39870438"
				year:  2025
			},
			{
				title: "Exploring Talarozole as a Novel Therapeutic Approach for Osteoarthritis: Insights From Experimental Studies."
				pmid:  "38292917"
				year:  2024
			},
			{
				title: "Change of Dendritic Cell Subsets Involved in Protection Against Listeria monocytogenes Infection in Short-Term-Fasted Mice."
				pmid:  "35573152"
				year:  2022
			},
		]
	}
	"AXIN2": {
		_in_pubmed:     true
		pubmed_gene_id: "8313"
		pubmed_total:   200
		pubmed_recent:  79
		pubmed_papers: [
			{
				title: "Unlocking predictive genetic factors with artificial intelligence: relationship between dental impaction and hypodontia evaluated via association-rule algorithms: a case-control study."
				pmid:  "41489795"
				year:  2026
			},
			{
				title: "Dissecting the Genetic Contribution of Tooth Agenesis."
				pmid:  "41226524"
				year:  2025
			},
			{
				title: "AXIN2 variants, tooth agenesis, and cancer risk: a systematic review."
				pmid:  "41188821"
				year:  2025
			},
		]
	}
	"BMP2": {
		_in_pubmed:     true
		pubmed_gene_id: "650"
		pubmed_total:   1707
		pubmed_recent:  488
		pubmed_papers: [
			{
				title: "Lyophilized L-PRF enhances the bioactivity and rheological properties of 3D-printed and bioprinted scaffolds containing Dental pulp stem cells."
				pmid:  "41656139"
				year:  2026
			},
			{
				title: "Thiamet-G facilitates reparative dentin formation via modulating O-GlcNAcylation and inflammation."
				pmid:  "41624019"
				year:  2025
			},
			{
				title: "Novel demineralized freeze-dried bovine bone xenograft nanoparticles (DFDBBX-NPs) for enhanced bone repair."
				pmid:  "41609504"
				year:  2026
			},
		]
	}
	"BMP4": {
		_in_pubmed:     true
		pubmed_gene_id: "652"
		pubmed_total:   714
		pubmed_recent:  0
	}
	"BMP7": {
		_in_pubmed:     true
		pubmed_gene_id: "655"
		pubmed_total:   284
		pubmed_recent:  58
		pubmed_papers: [
			{
				title: "Osteogenic Efficacy of Porous Glass Microspheres-Loaded Dental Pulp Stem Cell-Derived Exosomes for Orthobiologic Applications."
				pmid:  "41556598"
				year:  2026
			},
			{
				title: "BMP7 alleviates trigeminal neuralgia by suppressing oxidative stress and activation of satellite glial cells via the NRF2/HO-1 pathway."
				pmid:  "41534727"
				year:  2026
			},
			{
				title: "Evaluation of Human Dental Pulp Stem Cells Expressing BMP2/7 Heterodimers in a Doxycycline-Inducible Manner."
				pmid:  "41463360"
				year:  2025
			},
		]
	}
	"CDH11": {
		_in_pubmed:     true
		pubmed_gene_id: "1009"
		pubmed_total:   13
		pubmed_recent:  5
	}
	"CDH2": {
		_in_pubmed:     true
		pubmed_gene_id: "1000"
		pubmed_total:   25
		pubmed_recent:  10
		pubmed_papers: [
			{
				title: "The Redox-Adhesion-Exosome (RAX) Hub in Cancer: Lipid Peroxidation-Driven EMT Plasticity and Ferroptosis Defense with HNE/MDA Signaling and Lipidomic Perspectives."
				pmid:  "41462674"
				year:  2025
			},
			{
				title: "Effect of CDH1 and CDH2 genes polymorphisms in oral squamous cell carcinoma susceptibility in a sample of Iranian population: A case-control study."
				pmid:  "37091359"
				year:  2023
			},
			{
				title: "Goji berry (Lycium barbarum) inhibits the proliferation, adhesion, and migration of oral cancer cells by inhibiting the ERK, AKT, and CyclinD cell signaling pathways: an in-vitro study."
				pmid:  "36761830"
				year:  2022
			},
		]
	}
	"CDH6": {
		_in_pubmed:     true
		pubmed_gene_id: "1004"
		pubmed_total:   6
		pubmed_recent:  0
	}
	"CHD7": {
		_in_pubmed:     true
		pubmed_gene_id: "55636"
		pubmed_total:   115
		pubmed_recent:  0
		pubmed_papers: [
			{
				title: "Olfactory dysfunction in CHARGE syndrome: a systematic review of prevalence, assessment methods, and clinical correlates."
				pmid:  "41313596"
				year:  2025
			},
			{
				title: "Analysis of the clinical features of neurocristopathy-related hearing loss and how these relate to outcomes after cochlear implantation."
				pmid:  "41271950"
				year:  2025
			},
			{
				title: "CHD7 regulates cardiac neural crest cell differentiation through SOX5-mediated self-activation."
				pmid:  "41210995"
				year:  2025
			},
		]
	}
	"CTNNB1": {
		_in_pubmed:     true
		pubmed_gene_id: "1499"
		pubmed_total:   113
		pubmed_recent:  54
		pubmed_papers: [
			{
				title: "Oral-Gut Microbiota Crosstalk and Epigenetic Targets in Metabolic and Neuropsychiatric Diseases."
				pmid:  "41228440"
				year:  2025
			},
			{
				title: "Expanding the Molecular Characterization of Adenoid Ameloblastoma by Assessing a Panel of Oncogenes and Tumor Suppressor Genes."
				pmid:  "41109353"
				year:  2026
			},
			{
				title: "A scientometric study on Wnt and Notch signaling pathways in oral potentially malignant disorders and oral cancer."
				pmid:  "41040585"
				year:  2025
			},
		]
	}
	"CXCR4": {
		_in_pubmed:     true
		pubmed_gene_id: "7852"
		pubmed_total:   301
		pubmed_recent:  0
	}
	"DCT": {
		_in_pubmed:     true
		pubmed_gene_id: "1638"
		pubmed_total:   170
		pubmed_recent:  38
		pubmed_papers: [
			{
				title: "Targeting the melanocytes of the inner ear: A comparison of different CreER lines."
				pmid:  "41397511"
				year:  2026
			},
			{
				title: "Fabricated modified compomer bearing CF/SBA-15 nanomaterials: Physicochemical and antibacterial properties."
				pmid:  "41241588"
				year:  2026
			},
			{
				title: "Antibacterial effects of bioactive restorative dental materials on Streptococcus mutans: An in vitro study using the direct contact test."
				pmid:  "41091362"
				year:  2025
			},
		]
	}
	"DLL1": {
		_in_pubmed:     true
		pubmed_gene_id: "28514"
		pubmed_total:   33
		pubmed_recent:  8
		pubmed_papers: [
			{
				title: "Regulation of osteogenic differentiation of boronized Ti6Al4V/HA composite involving TRIP13-PI3K/Akt signaling pathway."
				pmid:  "41581318"
				year:  2026
			},
			{
				title: "Joslin Kidney Panel of Circulating Proteins: A Tool for ESKD Risk Discrimination and Individualized Diabetic Kidney Disease Treatment."
				pmid:  "41071620"
				year:  2026
			},
			{
				title: "Regulation of feather length: FGF/IGF signaling and NOTCH/YAP modulation of progenitor cell topology."
				pmid:  "40845092"
				year:  2025
			},
		]
	}
	"DLX2": {
		_in_pubmed:     true
		pubmed_gene_id: "1746"
		pubmed_total:   103
		pubmed_recent:  12
		pubmed_papers: [
			{
				title: "A missense variant in ASCL5 leads to lobodontia."
				pmid:  "41673016"
				year:  2026
			},
			{
				title: "DLX2 acts as a pioneer factor and drives Msx1(+) ectomesenchyme formation from embryonic stem cells."
				pmid:  "41533791"
				year:  2026
			},
			{
				title: "The Molecular Mechanism of Craniofacial Cartilage Deformity Induced by High Glucose in Zebrafish."
				pmid:  "41020809"
				year:  2025
			},
		]
	}
	"DLX3": {
		_in_pubmed:     true
		pubmed_gene_id: "1747"
		pubmed_total:   124
		pubmed_recent:  26
		pubmed_papers: [
			{
				title: "Suppression of distal-less homeobox 3 increased alveolar bone mass in mouse tooth socket by targeting thrombospondin 1."
				pmid:  "41585139"
				year:  2026
			},
			{
				title: "Genetic and environmental determinants of dental fluorosis: a case‒control study of DLX3, ESR1, and ESR2 variants in a high-fluoride region of Mexico."
				pmid:  "41174690"
				year:  2025
			},
			{
				title: "Dento-Craniofacial Features of Tricho-Dento-Osseous Syndrome: A Systematic Review and Meta-Analysis."
				pmid:  "40402097"
				year:  2025
			},
		]
	}
	"DLX5": {
		_in_pubmed:     true
		pubmed_gene_id: "1749"
		pubmed_total:   192
		pubmed_recent:  35
		pubmed_papers: [
			{
				title: "Acellular dental pulp and allogeneic cells for strategic pulp regeneration."
				pmid:  "41687189"
				year:  2026
			},
			{
				title: "Pleiotropic function of Dlx5/6 in the development of mammalian vocal and auditory organs."
				pmid:  "41329676"
				year:  2025
			},
			{
				title: "Distal-less homeobox 5 transactivated by MYCN contributes to progression of neuroblastoma through AKT signaling pathway."
				pmid:  "41135749"
				year:  2025
			},
		]
	}
	"DLX6": {
		_in_pubmed:     true
		pubmed_gene_id: "1750"
		pubmed_total:   60
		pubmed_recent:  14
		pubmed_papers: [
			{
				title: "Profiling and functional characterization of long noncoding RNAs during human tooth development."
				pmid:  "40346090"
				year:  2025
			},
			{
				title: "Twist1 Acts Upstream of the Dlx5-Hand2 Pathway to Pattern the Mammalian Jaw."
				pmid:  "39707586"
				year:  2025
			},
			{
				title: "Regulatory elements in SEM1-DLX5-DLX6 (7q21.3) locus contribute to genetic control of coronal nonsyndromic craniosynostosis and bone density-related traits."
				pmid:  "39345948"
				year:  2024
			},
		]
	}
	"ECE1": {
		_in_pubmed:     true
		pubmed_gene_id: "1889"
		pubmed_total:   51
		pubmed_recent:  14
		pubmed_papers: [
			{
				title: "Candida albicans-induced ubiquitination of EGFR reveals novel host-fungal interaction pathways."
				pmid:  "41524399"
				year:  2026
			},
			{
				title: "The combinatorial action of hyphal growth and candidalysin is critical for promoting Candida albicans oropharyngeal infection."
				pmid:  "41294335"
				year:  2026
			},
			{
				title: "Exploring the evolutionary conservation and functional implications of Endothelin Converting Enzyme 1 (ECE1) in lamprey (Lethenteron reissneri)."
				pmid:  "41099905"
				year:  2025
			},
		]
	}
	"EDN1": {
		_in_pubmed:     true
		pubmed_gene_id: "1906"
		pubmed_total:   80
		pubmed_recent:  17
		pubmed_papers: [
			{
				title: "Lateral mandibular ridge: A unique feature of the auriculocondylar syndrome."
				pmid:  "41124729"
				year:  2026
			},
			{
				title: "Targeting IL6-Edn1-FoxO1 axis enables lung growth in mechanically ventilated newborn mice."
				pmid:  "41067869"
				year:  2025
			},
			{
				title: "The Gq/11 family of Gα subunits is necessary and sufficient for lower jaw development."
				pmid:  "40171762"
				year:  2025
			},
		]
	}
	"EDN3": {
		_in_pubmed:     true
		pubmed_gene_id: "1908"
		pubmed_total:   69
		pubmed_recent:  7
		pubmed_papers: [
			{
				title: "Endothelin-3 and T-type Ca(2+) channels drive enteric neural crest cell calcium activity, contractility and migration."
				pmid:  "41559055"
				year:  2026
			},
			{
				title: "Enteric neural crest development in Astyanax mexicanus surface fish and cavefish."
				pmid:  "40554892"
				year:  2025
			},
			{
				title: "Enteric neural crest development in Astyanax mexicanus surface fish and cavefish."
				pmid:  "40060476"
				year:  2025
			},
		]
	}
	"EDNRA": {
		_in_pubmed:     true
		pubmed_gene_id: "1909"
		pubmed_total:   49
		pubmed_recent:  7
	}
	"EDNRB": {
		_in_pubmed:     true
		pubmed_gene_id: "1910"
		pubmed_total:   155
		pubmed_recent:  25
		pubmed_papers: [
			{
				title: "Endothelin-3 and T-type Ca(2+) channels drive enteric neural crest cell calcium activity, contractility and migration."
				pmid:  "41559055"
				year:  2026
			},
			{
				title: "Combinatorial multiomic analysis from a pedigree of Sox10(Dom) Hirschsprung mice implicates Dach1 as a modifier of Enteric Nervous System development."
				pmid:  "41279280"
				year:  2025
			},
			{
				title: "Single-cell transcriptome profiling reveals altered neural crest cell dynamics and novel biomarkers in EDNRB mutant mice with Hirschsprung's disease phenotype."
				pmid:  "41262530"
				year:  2026
			},
		]
	}
	"ERBB3": {
		_in_pubmed:     true
		pubmed_gene_id: "2065"
		pubmed_total:   65
		pubmed_recent:  16
		pubmed_papers: [
			{
				title: "Beyond cell-cell contact: therapeutic potential of Eph signaling in central nervous system tumors."
				pmid:  "41200151"
				year:  2025
			},
			{
				title: "Expanding the Molecular Characterization of Adenoid Ameloblastoma by Assessing a Panel of Oncogenes and Tumor Suppressor Genes."
				pmid:  "41109353"
				year:  2026
			},
			{
				title: "Role of Inflammation and the NF-κB Signaling Pathway in Hirschsprung's Disease."
				pmid:  "39199380"
				year:  2024
			},
		]
	}
	"ETS1": {
		_in_pubmed:     true
		pubmed_gene_id: "2113"
		pubmed_total:   65
		pubmed_recent:  16
		pubmed_papers: [
			{
				title: "ETS1 Orchestrates a Hybrid EMT Program Driving in vivo Metastasis and Immune Evasion."
				pmid:  "40777467"
				year:  2025
			},
			{
				title: "Reactivation of an embryonic cardiac neural crest transcriptional profile during zebrafish heart regeneration."
				pmid:  "40531881"
				year:  2025
			},
			{
				title: "Reactivation of an Embryonic Cardiac Neural Crest Transcriptional Subcircuit During Zebrafish Heart Regeneration."
				pmid:  "39868190"
				year:  2025
			},
		]
	}
	"EVC": {
		_in_pubmed:     true
		pubmed_gene_id: "2121"
		pubmed_total:   63
		pubmed_recent:  0
		pubmed_papers: [
			{
				title: "EVC protein regulates Sonic hedgehog signaling during human intervertebral disc development and degeneration."
				pmid:  "41550739"
				year:  2026
			},
			{
				title: "Case Report of a Novel EVC Gene Mutation in Ellis-van Creveld Syndrome: Implications for Pediatric Dental Management."
				pmid:  "41438176"
				year:  2025
			},
			{
				title: "Identification of a Novel EVC2 Variant in a Family with Non-Syndromic Tooth Agenesis and Its Potential Functional Implications."
				pmid:  "41300740"
				year:  2025
			},
		]
	}
	"FGF8": {
		_in_pubmed:     true
		pubmed_gene_id: "2253"
		pubmed_total:   302
		pubmed_recent:  39
		pubmed_papers: [
			{
				title: "Centriolar protein PIBF1 is required for craniofacial and forebrain development."
				pmid:  "40774570"
				year:  2025
			},
			{
				title: "Fibroblast growth factor 8: Multifaceted role in development and developmental disorder."
				pmid:  "40575596"
				year:  2025
			},
			{
				title: "Sprouty2/4 deficiency disrupts early signaling centers impacting chondrogenesis in the mouse forelimb."
				pmid:  "39906257"
				year:  2025
			},
		]
	}
	"FGFR1": {
		_in_pubmed:     true
		pubmed_gene_id: "2260"
		pubmed_total:   373
		pubmed_recent:  0
	}
	"FGFR2": {
		_in_pubmed:     true
		pubmed_gene_id: "2263"
		pubmed_total:   759
		pubmed_recent:  145
		pubmed_papers: [
			{
				title: "Analysis of Eya1 and Tbx1 mutants highlights interactions between the muscle and developing cartilage during external ear formation."
				pmid:  "41649345"
				year:  2026
			},
			{
				title: "A smart nanocomposite bioactive ink for controlled siRNA delivery in calvarial mesenchymal stromal cells as a minimally invasive treatment for craniosynostosis."
				pmid:  "41647289"
				year:  2026
			},
			{
				title: "Tracheal cartilaginous sleeve prevalence in syndromic craniosynostosis: A single institution study."
				pmid:  "41637834"
				year:  2026
			},
		]
	}
	"FGFR3": {
		_in_pubmed:     true
		pubmed_gene_id: "2261"
		pubmed_total:   361
		pubmed_recent:  65
		pubmed_papers: [
			{
				title: "Three-dimensional craniofacial imaging in children with achondroplasia treated with vosoritide."
				pmid:  "41340868"
				year:  2025
			},
			{
				title: "Isolated frontosphenoidal craniosynostosis with pathogenic FGFR3 variant: a case report and genetic insights."
				pmid:  "41216445"
				year:  2025
			},
			{
				title: "Crouzonodermoskeletal syndrome requires individualized surgical management: Scoping review of a rare complex craniofacial syndrome."
				pmid:  "41215833"
				year:  2025
			},
		]
	}
	"FN1": {
		_in_pubmed:     true
		pubmed_gene_id: "2335"
		pubmed_total:   71
		pubmed_recent:  49
		pubmed_papers: [
			{
				title: "Synergistic protective and regenerative effects of hyaluronic acid and polynucleotides against UVA-induced oxidative stress in dermal fibroblasts."
				pmid:  "41617959"
				year:  2026
			},
			{
				title: "Calcifying Aponeurotic Fibroma: A Review and Update."
				pmid:  "41482378"
				year:  2026
			},
			{
				title: "Comparative proteomic profiling of advanced, injectable, and titanium-prepared platelet rich fibrins (PRF): Insights into functional divergence and clinical potential."
				pmid:  "41419009"
				year:  2025
			},
		]
	}
	"FOXD3": {
		_in_pubmed:     true
		pubmed_gene_id: "27022"
		pubmed_total:   165
		pubmed_recent:  30
		pubmed_papers: [
			{
				title: "MEP glia share molecular features with oligodendrocytes while maintaining a distinct hybrid signature."
				pmid:  "41660199"
				year:  2026
			},
			{
				title: "Advancing knock-in approaches for robust genome editing in zebrafish."
				pmid:  "41630603"
				year:  2026
			},
			{
				title: "Neural crest cell recruitment and reprogramming as central drivers of embryonic limb regeneration."
				pmid:  "41433066"
				year:  2025
			},
		]
	}
	"GATA4": {
		_in_pubmed:     true
		pubmed_gene_id: "2626"
		pubmed_total:   65
		pubmed_recent:  14
		pubmed_papers: [
			{
				title: "Single-nuclei multiomics analysis identifies abnormal cardiomyocytes in a murine model of cardiac development."
				pmid:  "40721580"
				year:  2025
			},
			{
				title: "Sequencing in over 50,000 cases identifies coding and structural variation underlying atrial fibrillation risk."
				pmid:  "40050430"
				year:  2025
			},
			{
				title: "Effects of tefluthrin exposure on early life stages in zebrafish: Insights into cardiac and skeletal development, oxidative stress and apoptosis."
				pmid:  "39978106"
				year:  2025
			},
		]
	}
	"GBX2": {
		_in_pubmed:     true
		pubmed_gene_id: "2637"
		pubmed_total:   24
		pubmed_recent:  0
	}
	"GDNF": {
		_in_pubmed:     true
		pubmed_gene_id: "2668"
		pubmed_total:   225
		pubmed_recent:  35
		pubmed_papers: [
			{
				title: "Endothelin-3 and T-type Ca(2+) channels drive enteric neural crest cell calcium activity, contractility and migration."
				pmid:  "41559055"
				year:  2026
			},
			{
				title: "Retinol dehydrogenase 10-mediated retinoic acid signaling regulates the neural crest cell microenvironment during enteric nervous system formation."
				pmid:  "41511193"
				year:  2026
			},
			{
				title: "Cecal growth factors promote enteric neurosphere formation and hindgut colonization in the avian model."
				pmid:  "41488003"
				year:  2025
			},
		]
	}
	"GFRA1": {
		_in_pubmed:     true
		pubmed_gene_id: "2674"
		pubmed_total:   9
		pubmed_recent:  1
		pubmed_papers: [
			{
				title: "Mesenchymal cells regulate enteric neural crest cell migration via RET-GFRA1b trans-signaling."
				pmid:  "38581949"
				year:  2024
			},
			{
				title: "ChIP-Seq-Based Approach in Mouse Enteric Precursor Cells Reveals New Potential Genes with a Role in Enteric Nervous System Development and Hirschsprung Disease."
				pmid:  "33260622"
				year:  2020
			},
			{
				title: "Biological assessments of multifunctional hydrogel-decorated implantable neural cuff electrode for clinical neurology application."
				pmid:  "29127334"
				year:  2017
			},
		]
	}
	"HAND1": {
		_in_pubmed:     true
		pubmed_gene_id: "9421"
		pubmed_total:   53
		pubmed_recent:  11
		pubmed_papers: [
			{
				title: "Differential requirement of Hand1 during differentiation of lateral plate mesoderm lineages in Xenopus laevis."
				pmid:  "40523515"
				year:  2025
			},
			{
				title: "Cardiomyocyte Foxp1-Specific Deletion Promotes Post-injury Heart Regeneration via Targeting Usp20-HIF1ɑ-Hand1 Signaling Pathway."
				pmid:  "39899693"
				year:  2025
			},
			{
				title: "The role of heart and neural crest derivatives-expressed protein factors in pregnancy."
				pmid:  "39725090"
				year:  2025
			},
		]
	}
	"HAND2": {
		_in_pubmed:     true
		pubmed_gene_id: "9464"
		pubmed_total:   181
		pubmed_recent:  48
		pubmed_papers: [
			{
				title: "Non-invasive colorectal cancer biomarkers: HAND2 and GPM6A methylation in circulating tumour DNA."
				pmid:  "40682031"
				year:  2025
			},
			{
				title: "Lineage labeling with zebrafish hand2 Cre and CreERT2 recombinase CRISPR knock-ins."
				pmid:  "40135929"
				year:  2026
			},
			{
				title: "The role of heart and neural crest derivatives-expressed protein factors in pregnancy."
				pmid:  "39725090"
				year:  2025
			},
		]
	}
	"IRF6": {
		_in_pubmed:     true
		pubmed_gene_id: "3664"
		pubmed_total:   265
		pubmed_recent:  82
		pubmed_papers: [
			{
				title: "IRF6 Gene Polymorphisms Influence the Susceptibility of Nonsyndromic Cleft Lips With or Without Palate: A MOOSE-Compliant Meta-Analysis."
				pmid:  "41662226"
				year:  2026
			},
			{
				title: "Notch signaling in the embryonic ectoderm promotes periderm cell fate and represses mineralization of vibrissa hair follicles."
				pmid:  "41659514"
				year:  2026
			},
			{
				title: "Genetic Associations with Non-Syndromic Cleft Lip/Palate and Dental Caries in Kuwaiti Patients: A Case-Control Study."
				pmid:  "41590178"
				year:  2026
			},
		]
	}
	"ITGB1": {
		_in_pubmed:     true
		pubmed_gene_id: "3688"
		pubmed_total:   37
		pubmed_recent:  0
		pubmed_papers: [
			{
				title: "Transcriptomics Analysis of the Adipogenic Differentiation Mechanism of Bovine Adipose-Derived Neural Crest Stem Cells."
				pmid:  "40867681"
				year:  2025
			},
			{
				title: "Identification of neural crest and melanoma cancer cell invasion and migration genes using high-throughput screening and deep attention networks."
				pmid:  "40637615"
				year:  2026
			},
			{
				title: "A comparative study of the epithelial regeneration capacities of two biomaterials in vitro."
				pmid:  "40281524"
				year:  2025
			},
		]
	}
	"JAG1": {
		_in_pubmed:     true
		pubmed_gene_id: "182"
		pubmed_total:   56
		pubmed_recent:  0
	}
	"KIT": {
		_in_pubmed:     true
		pubmed_gene_id: "3815"
		pubmed_total:   2462
		pubmed_recent:  896
		pubmed_papers: [
			{
				title: "Effect of Music-Based Interventions on Dental Anxiety During Restorative Dental Treatment: A Randomized Controlled Trial."
				pmid:  "41682937"
				year:  2026
			},
			{
				title: "Comparative Analysis of Oral Bacterial Profiles in Parkinson's Disease According to Periodontal Status: A Clinical Case Series."
				pmid:  "41682213"
				year:  2026
			},
			{
				title: "Prolonging the preservation time of periodontal ligament cells in vitro: a new first-aid kit for tooth avulsion."
				pmid:  "41652450"
				year:  2026
			},
		]
	}
	"LEF1": {
		_in_pubmed:     true
		pubmed_gene_id: "51176"
		pubmed_total:   142
		pubmed_recent:  29
	}
	"MEF2C": {
		_in_pubmed:     true
		pubmed_gene_id: "4208"
		pubmed_total:   62
		pubmed_recent:  21
		pubmed_papers: [
			{
				title: "Single-Nucleus RNA Sequencing Reveals Mid-Gestational Neurodevelopment Features in the Superior Temporal Plane from Fetuses with Nonsyndromic Cleft Lip and Palate."
				pmid:  "41117157"
				year:  2026
			},
			{
				title: "Single-nuclei multiomics analysis identifies abnormal cardiomyocytes in a murine model of cardiac development."
				pmid:  "40721580"
				year:  2025
			},
			{
				title: "Mapping the Interactions Among Class IIa Histone Deacetylases and Myocyte Enhancer Factor 2s."
				pmid:  "40478640"
				year:  2025
			},
		]
	}
	"MITF": {
		_in_pubmed:     true
		pubmed_gene_id: "4286"
		pubmed_total:   214
		pubmed_recent:  45
		pubmed_papers: [
			{
				title: "Malignant Craniofacial Perivascular Epithelioid Cell Tumor: A Review of Literature With a Rare Presentation."
				pmid:  "41367329"
				year:  2025
			},
			{
				title: "Transcription factor MITF regulates masseter muscle growth and development."
				pmid:  "41277713"
				year:  2025
			},
			{
				title: "The Role of the Microenvironment on the Localization of Hair and Skin Nonuniform Pigmented Spots in Mice with a Targeted Mutation in the Endothelin B Receptor."
				pmid:  "41101632"
				year:  2025
			},
		]
	}
	"MMP2": {
		_in_pubmed:     true
		pubmed_gene_id: "4313"
		pubmed_total:   764
		pubmed_recent:  225
	}
	"MMP9": {
		_in_pubmed:     true
		pubmed_gene_id: "4318"
		pubmed_total:   1069
		pubmed_recent:  406
		pubmed_papers: [
			{
				title: "Loss of mechanical stress induces synovitis, fibrosis and articular cartilage degeneration via distinct synovial cell subsets."
				pmid:  "41663755"
				year:  2026
			},
			{
				title: "The potential anti-caries activity of theaflavins (TFs): investigation of their inhibitory effect on matrix metalloproteinase-9 (MMP-9) and the underlying mechanism."
				pmid:  "41661095"
				year:  2026
			},
			{
				title: "Evaluation of Inflammatory Mediators, pulpal blood pH and oxygen saturation in teeth with pulpitis."
				pmid:  "41654292"
				year:  2026
			},
		]
	}
	"MSX1": {
		_in_pubmed:     true
		pubmed_gene_id: "4487"
		pubmed_total:   500
		pubmed_recent:  84
		pubmed_papers: [
			{
				title: "Acellular dental pulp and allogeneic cells for strategic pulp regeneration."
				pmid:  "41687189"
				year:  2026
			},
			{
				title: "DLX2 acts as a pioneer factor and drives Msx1(+) ectomesenchyme formation from embryonic stem cells."
				pmid:  "41533791"
				year:  2026
			},
			{
				title: "Wnt3a promotes in situ dentin formation through NKD1-MSX1 axis-mediated odontogenic differentiation of dental pulp stem cells."
				pmid:  "41526338"
				year:  2026
			},
		]
	}
	"MSX2": {
		_in_pubmed:     true
		pubmed_gene_id: "4488"
		pubmed_total:   299
		pubmed_recent:  22
		pubmed_papers: [
			{
				title: "Leveraging the genetics of human face shape boosts the discovery of orofacial cleft risk loci."
				pmid:  "41674607"
				year:  2026
			},
			{
				title: "Identification of Novel and Rare Gene Variants in Cleft Lip/Palate Patients From Kuwaiti Consanguineous Families by Exome Sequencing."
				pmid:  "41041957"
				year:  2026
			},
			{
				title: "The genetic basis of tooth impaction: a systematic review."
				pmid:  "40982116"
				year:  2025
			},
		]
	}
	"MYCN": {
		_in_pubmed:     true
		pubmed_gene_id: "4613"
		pubmed_total:   220
		pubmed_recent:  0
	}
	"NF1": {
		_in_pubmed:     true
		pubmed_gene_id: "4763"
		pubmed_total:   357
		pubmed_recent:  0
	}
	"NGFR": {
		_in_pubmed:     true
		pubmed_gene_id: "4804"
		pubmed_total:   69
		pubmed_recent:  16
		pubmed_papers: [
			{
				title: "Synergistic activity of S63845 and parthenolide to overcome acquired resistance to MEK1/2 inhibitor in melanoma cells: Mechanisms and therapeutic potential."
				pmid:  "40424823"
				year:  2025
			},
			{
				title: "Histological characterisation of the horn bud region in 58 day old bovine fetuses."
				pmid:  "39177099"
				year:  2024
			},
			{
				title: "PRRX1 silencing is required for metastatic outgrowth in melanoma and is an independent prognostic of reduced survival in patients."
				pmid:  "38978350"
				year:  2024
			},
		]
	}
	"NKX2-5": {
		_in_pubmed:     true
		pubmed_gene_id: "1482"
		pubmed_total:   53
		pubmed_recent:  15
		pubmed_papers: [
			{
				title: "Understanding the role of Shroom3 in the developing mouse myocardium."
				pmid:  "40920782"
				year:  2025
			},
			{
				title: "Uric Acid Disrupts Heart Development in Zebrafish by Inhibiting the Wnt Signaling Pathway."
				pmid:  "40839160"
				year:  2025
			},
			{
				title: "Single-Cell Transcriptomics and Lineage Tracing Unveil Parallels in Lymphatic Muscle and Venous Smooth Muscle Development, Identity, and Function."
				pmid:  "40371470"
				year:  2025
			},
		]
	}
	"NOTCH1": {
		_in_pubmed:     true
		pubmed_gene_id: "4851"
		pubmed_total:   270
		pubmed_recent:  75
		pubmed_papers: [
			{
				title: "Notch signaling in the embryonic ectoderm promotes periderm cell fate and represses mineralization of vibrissa hair follicles."
				pmid:  "41659514"
				year:  2026
			},
			{
				title: "Chronic stress drives ovarian cancer progression via myeloid-derived suppressor cells infiltration and Notch signaling pathway activation."
				pmid:  "41488655"
				year:  2025
			},
			{
				title: "Comprehensive transcriptomic analysis reveals canonical and novel pathways modulated by nanoceria in mammalian retinal degeneration."
				pmid:  "41484209"
				year:  2026
			},
		]
	}
	"NOTCH2": {
		_in_pubmed:     true
		pubmed_gene_id: "4853"
		pubmed_total:   105
		pubmed_recent:  33
		pubmed_papers: [
			{
				title: "Temporal Bone CT Findings in Hajdu-Cheney Syndrome: Case Report with Review of the Literature."
				pmid:  "41326232"
				year:  2025
			},
			{
				title: "Clinical and Molecular Genetic Study of an Alagille Syndrome Type 1 Case."
				pmid:  "41273573"
				year:  2026
			},
			{
				title: "A combined in-silico and in-vitro evaluation of cyanoacrylate-based dental materials as an adhesive for applications in prosthodontics: molecular docking and cytocompatibility analysis."
				pmid:  "41193923"
				year:  2025
			},
		]
	}
	"NR2F1": {
		_in_pubmed:     true
		pubmed_gene_id: "7025"
		pubmed_total:   14
		pubmed_recent:  9
		pubmed_papers: [
			{
				title: "Integration of Nuclear Receptors into a Schwann cell Gene Regulatory Network."
				pmid:  "41279248"
				year:  2025
			},
			{
				title: "Cranial neural crest shortage leads to extensive craniofacial anomalies in mice mutant for the NR2F1/2 nuclear receptors."
				pmid:  "41276060"
				year:  2026
			},
			{
				title: "FGF9-FGFR2 Signaling via Osteocytes-Preosteoblasts Crosstalks to Mediate Mechanotransduction-Driven Intramembranous Osteogenesis in the Underdeveloped Maxilla."
				pmid:  "40913526"
				year:  2025
			},
		]
	}
	"NR2F2": {
		_in_pubmed:     true
		pubmed_gene_id: "7026"
		pubmed_total:   12
		pubmed_recent:  5
		pubmed_papers: [
			{
				title: "Sjögren's patient subgroups identified through whole genome DNA methylation profiling."
				pmid:  "41634784"
				year:  2026
			},
			{
				title: "Integration of Nuclear Receptors into a Schwann cell Gene Regulatory Network."
				pmid:  "41279248"
				year:  2025
			},
			{
				title: "Cranial neural crest shortage leads to extensive craniofacial anomalies in mice mutant for the NR2F1/2 nuclear receptors."
				pmid:  "41276060"
				year:  2026
			},
		]
	}
	"NRP1": {
		_in_pubmed:     true
		pubmed_gene_id: "8829"
		pubmed_total:   55
		pubmed_recent:  14
	}
	"PAX3": {
		_in_pubmed:     true
		pubmed_gene_id: "5077"
		pubmed_total:   346
		pubmed_recent:  48
		pubmed_papers: [
			{
				title: "Mediolateral neural patterning during gastrulation precedes dorsoventral patterning in chick and frog."
				pmid:  "41638547"
				year:  2026
			},
			{
				title: "rs2033806 at PAX3 Gene Associated with Non-syndromic Oral Cleft among the Chinese Population."
				pmid:  "41498502"
				year:  2025
			},
			{
				title: "Targeting the melanocytes of the inner ear: A comparison of different CreER lines."
				pmid:  "41397511"
				year:  2026
			},
		]
	}
	"PAX6": {
		_in_pubmed:     true
		pubmed_gene_id: "5080"
		pubmed_total:   158
		pubmed_recent:  0
	}
	"PAX7": {
		_in_pubmed:     true
		pubmed_gene_id: "5081"
		pubmed_total:   174
		pubmed_recent:  55
		pubmed_papers: [
			{
				title: "Mediolateral neural patterning during gastrulation precedes dorsoventral patterning in chick and frog."
				pmid:  "41638547"
				year:  2026
			},
			{
				title: "Identification of key genes for mandibular prognathism in Duolang sheep via genome-wide association analysis."
				pmid:  "41635791"
				year:  2025
			},
			{
				title: "Duplicated, Translocated Upper Lip and Maxilla: An Extremely Rare Congenital Craniofacial Anomaly With Novel Genetic Findings."
				pmid:  "41540721"
				year:  2026
			},
		]
	}
	"PHOX2B": {
		_in_pubmed:     true
		pubmed_gene_id: "8929"
		pubmed_total:   176
		pubmed_recent:  38
		pubmed_papers: [
			{
				title: "A novel molecular classifier enabling identification and prediction on immunotherapeutic response for MYCN-low pediatric neuroblastoma."
				pmid:  "41553393"
				year:  2026
			},
			{
				title: "Peripheral nerve transection predominantly drives sympathetic nerve sprouting in mouse dorsal root ganglia."
				pmid:  "41553172"
				year:  2026
			},
			{
				title: "Aberrant neural crest cells migration leads to melanocyte presence in the umbilical cord."
				pmid:  "41548465"
				year:  2026
			},
		]
	}
	"PLXNA2": {
		_in_pubmed:     true
		pubmed_gene_id: "5362"
		pubmed_total:   9
		pubmed_recent:  2
		pubmed_papers: [
			{
				title: "RNA Sequencing Revealed a Weak Response of Gingival Fibroblasts Exposed to Hyaluronic Acid."
				pmid:  "39768125"
				year:  2024
			},
			{
				title: "Human Genetics of Truncus Arteriosus."
				pmid:  "38884753"
				year:  2024
			},
			{
				title: "PLXNA2 identified as a candidate gene by genome-wide association analysis for mandibular prognathism in human chondrocytes."
				pmid:  "30271602"
				year:  2018
			},
		]
	}
	"PMEL": {
		_in_pubmed:     true
		pubmed_gene_id: "6490"
		pubmed_total:   10
		pubmed_recent:  6
		pubmed_papers: [
			{
				title: "Congenital Cutaneous Neurocristic Hamartoma of the Scalp with Poor Melanin Content."
				pmid:  "40232281"
				year:  2025
			},
			{
				title: "SMARCB1-deficient malignant melanocytic uveal tumours: a new neural crest-derived tumour entity with SMARCB1-related germline predisposition."
				pmid:  "39853675"
				year:  2025
			},
			{
				title: "Requirements for anti-aquaporin 5 autoantibody production in a mouse model."
				pmid:  "37718989"
				year:  2023
			},
		]
	}
	"RAC1": {
		_in_pubmed:     true
		pubmed_gene_id: "5879"
		pubmed_total:   218
		pubmed_recent:  55
		pubmed_papers: [
			{
				title: "Force coordination distinguishes epithelial and mesenchymal modes of collective chemotaxis."
				pmid:  "41563116"
				year:  2026
			},
			{
				title: "The role of Rho GTPases in facial morphogenesis."
				pmid:  "41536260"
				year:  2026
			},
			{
				title: "Familial Presentation of a Rare NCKAP1 Splice-Site Variant Associated With a Neurodevelopmental Disorder and Cutaneous Manifestations."
				pmid:  "41531171"
				year:  2026
			},
		]
	}
	"RARA": {
		_in_pubmed:     true
		pubmed_gene_id: "5914"
		pubmed_total:   26
		pubmed_recent:  5
		pubmed_papers: [
			{
				title: "Acute Promyelocytic Leukemia: Pathophysiology, Diagnosis and Clinical Management."
				pmid:  "41440764"
				year:  2025
			},
			{
				title: "De novo variants implicate chromatin modification, transcriptional regulation, and retinoic acid signaling in syndromic craniosynostosis."
				pmid:  "37086723"
				year:  2023
			},
			{
				title: "Sasa veitchii extracts protect phenytoin-induced cell proliferation inhibition in human lip mesenchymal cells through modulation of miR-27b-5p."
				pmid:  "37005285"
				year:  2023
			},
		]
	}
	"RET": {
		_in_pubmed:     true
		pubmed_gene_id: "5979"
		pubmed_total:   549
		pubmed_recent:  0
	}
	"RHOA": {
		_in_pubmed:     true
		pubmed_gene_id: "387"
		pubmed_total:   242
		pubmed_recent:  60
		pubmed_papers: [
			{
				title: "Ameloblastin Amphipathic Helix Motif mediates Ameloblast Polarization and Prismatic Enamel Formation via a RhoA Signaling Pathway."
				pmid:  "41646298"
				year:  2026
			},
			{
				title: "The role of Rho GTPases in facial morphogenesis."
				pmid:  "41536260"
				year:  2026
			},
			{
				title: "Integrated Genetic Analyses Identified T-cell Neoplasms Other Than Adult T-cell Leukemia/Lymphoma in HTLV-1 Carriers."
				pmid:  "41428991"
				year:  2025
			},
		]
	}
	"RUNX2": {
		_in_pubmed:     true
		pubmed_gene_id: "860"
		pubmed_total:   2325
		pubmed_recent:  938
		pubmed_papers: [
			{
				title: "Circ_015350 Mediates Odonto/osteogenic Differentiation in Different Stem Cells."
				pmid:  "41673513"
				year:  2026
			},
			{
				title: "Transgenic high expression of EphB4 in canine periodontal ligament stem cells modulates osteogenic differentiation and migration in cPDLSCs."
				pmid:  "41664138"
				year:  2026
			},
			{
				title: "Lyophilized L-PRF enhances the bioactivity and rheological properties of 3D-printed and bioprinted scaffolds containing Dental pulp stem cells."
				pmid:  "41656139"
				year:  2026
			},
		]
	}
	"SEMA3A": {
		_in_pubmed:     true
		pubmed_gene_id: "10371"
		pubmed_total:   85
		pubmed_recent:  23
		pubmed_papers: [
			{
				title: "The transcription factor ZFP64 promotes activity-dependent synapse elimination during postnatal cerebellar development."
				pmid:  "40546958"
				year:  2025
			},
			{
				title: "An atlas of early human mandibular endochondral and osteogenic paracrine signaling regions of Meckel's cartilage."
				pmid:  "40096606"
				year:  2025
			},
			{
				title: "Non-Canonical Wnt16 and microRNA-145 Mediate the Response of Human Bone Marrow Stromal Cells to Additively Manufactured Porous 3-Dimensional Biomimetic Titanium-Aluminum-Vanadium Constructs."
				pmid:  "39937002"
				year:  2025
			},
		]
	}
	"SEMA3C": {
		_in_pubmed:     true
		pubmed_gene_id: "10512"
		pubmed_total:   19
		pubmed_recent:  7
		pubmed_papers: [
			{
				title: "The aberrant migration and differentiation of neural crest cells are associated with the production of HVP in bearded chicken."
				pmid:  "41236583"
				year:  2025
			},
			{
				title: "Human Genetics of Truncus Arteriosus."
				pmid:  "38884753"
				year:  2024
			},
			{
				title: "Paired-Related Homeobox 1-Positive Cells Are Needed for Osseointegration."
				pmid:  "38498783"
				year:  2024
			},
		]
	}
	"SHH": {
		_in_pubmed:     true
		pubmed_gene_id: "6469"
		pubmed_total:   724
		pubmed_recent:  0
	}
	"SMAD1": {
		_in_pubmed:     true
		pubmed_gene_id: "4086"
		pubmed_total:   250
		pubmed_recent:  80
		pubmed_papers: [
			{
				title: "Development of a zebrafish model of Loeys-Dietz syndrome through tgfbr2b knockdown."
				pmid:  "41629640"
				year:  2026
			},
			{
				title: "FK506 enhances bone morphogenetic protein 9-induced cementoblast differentiation in human cementoblast-lineage cells."
				pmid:  "41264113"
				year:  2025
			},
			{
				title: "fam20b-dependent proteoglycans do not affect dermal bone formation and fin regeneration, but Bmp signalling promotes fin regenerate outgrowth."
				pmid:  "41205547"
				year:  2025
			},
		]
	}
	"SNAI1": {
		_in_pubmed:     true
		pubmed_gene_id: "6615"
		pubmed_total:   44
		pubmed_recent:  10
		pubmed_papers: [
			{
				title: "Anti-metastatic potential of flavonoids for the treatment of cancers: focus on epithelial-mesenchymal transition (EMT) process."
				pmid:  "40434422"
				year:  2025
			},
			{
				title: "Resveratrol is an inhibitory polyphenol of epithelial-mesenchymal transition induced by Fusobacterium nucleatum."
				pmid:  "38290225"
				year:  2024
			},
			{
				title: "Human Oral Mucosa as a Potentially Effective Source of Neural Crest Stem Cells for Clinical Practice."
				pmid:  "37759439"
				year:  2023
			},
		]
	}
	"SNAI2": {
		_in_pubmed:     true
		pubmed_gene_id: "6591"
		pubmed_total:   57
		pubmed_recent:  18
		pubmed_papers: [
			{
				title: "Dynamic and non-uniform expression of key transcription factors provides novel insights into the emergence of neural crest cells at the neural plate border."
				pmid:  "41256729"
				year:  2025
			},
			{
				title: "Reaching a cell monolayer at the end of hiPSC differentiation enhances neural crest lineage commitment."
				pmid:  "40906749"
				year:  2025
			},
			{
				title: "Full length transcriptomic profiling reveals insights into the white coat phenotype in Waardenburg syndrome mice harboring the Mitf R324del mutation."
				pmid:  "40745198"
				year:  2025
			},
		]
	}
	"SOX10": {
		_in_pubmed:     true
		pubmed_gene_id: "6663"
		pubmed_total:   696
		pubmed_recent:  187
		pubmed_papers: [
			{
				title: "SOX10 Mutation of Waardenburg Syndrome With Hypogonadism: A Report of 2 Cases."
				pmid:  "41684881"
				year:  2026
			},
			{
				title: "PRDM16 is necessary for sensory neuronal development in the Trigeminal Ganglion."
				pmid:  "41676534"
				year:  2026
			},
			{
				title: "Modulating O-GlcNAcylation Alters Salivary Acinar Cell Differentiation."
				pmid:  "41549625"
				year:  2026
			},
		]
	}
	"SOX2": {
		_in_pubmed:     true
		pubmed_gene_id: "6657"
		pubmed_total:   562
		pubmed_recent:  167
		pubmed_papers: [
			{
				title: "Circulating lncRNAs Remark Expression Profile of Cerebrovascular Malformation Endothelial Cells."
				pmid:  "41674478"
				year:  2026
			},
			{
				title: "Mechanical Memory and NF-κB Signaling in Dental Pulp Stem Cell Odontogenic Differentiation."
				pmid:  "41520920"
				year:  2026
			},
			{
				title: "The epigenetic rejuvenation promise: Partial reprogramming as a therapeutic strategy for aging and disease."
				pmid:  "41490578"
				year:  2026
			},
		]
	}
	"SOX5": {
		_in_pubmed:     true
		pubmed_gene_id: "6660"
		pubmed_total:   39
		pubmed_recent:  9
		pubmed_papers: [
			{
				title: "Machine learning-based prediction of drug response in ischemia reperfusion animal model."
				pmid:  "41331264"
				year:  2025
			},
			{
				title: "CHD7 regulates cardiac neural crest cell differentiation through SOX5-mediated self-activation."
				pmid:  "41210995"
				year:  2025
			},
			{
				title: "The microRNA-34b-3p/SOX5 axis regulates cellular activities and tumor angiogenesis in oral squamous cell carcinoma."
				pmid:  "41207030"
				year:  2026
			},
		]
	}
	"SOX8": {
		_in_pubmed:     true
		pubmed_gene_id: "30812"
		pubmed_total:   43
		pubmed_recent:  8
		pubmed_papers: [
			{
				title: "Dynamic and non-uniform expression of key transcription factors provides novel insights into the emergence of neural crest cells at the neural plate border."
				pmid:  "41256729"
				year:  2025
			},
			{
				title: "Missense variants weakening a SOX9 phosphodegron linked to odontogenesis defects, scoliosis, and other skeletal features."
				pmid:  "39797402"
				year:  2025
			},
			{
				title: "Application of spatial transcriptomics analysis using the Visium system for the mouse nasal cavity after intranasal vaccination."
				pmid:  "37545501"
				year:  2023
			},
		]
	}
	"SOX9": {
		_in_pubmed:     true
		pubmed_gene_id: "6662"
		pubmed_total:   610
		pubmed_recent:  0
	}
	"TBX1": {
		_in_pubmed:     true
		pubmed_gene_id: "6899"
		pubmed_total:   175
		pubmed_recent:  32
	}
	"TBX5": {
		_in_pubmed:     true
		pubmed_gene_id: "6910"
		pubmed_total:   35
		pubmed_recent:  5
		pubmed_papers: [
			{
				title: "Single-nuclei multiomics analysis identifies abnormal cardiomyocytes in a murine model of cardiac development."
				pmid:  "40721580"
				year:  2025
			},
			{
				title: "Human Genetics of Tetralogy of Fallot and Double-Outlet Right Ventricle."
				pmid:  "38884738"
				year:  2024
			},
			{
				title: "Cardiac Transcription Factors and Regulatory Networks."
				pmid:  "38884718"
				year:  2024
			},
		]
	}
	"TCOF1": {
		_in_pubmed:     true
		pubmed_gene_id: "6949"
		pubmed_total:   131
		pubmed_recent:  35
		pubmed_papers: [
			{
				title: "Case Report: A novel heterozygous variant of the TCOF1 gene in Treacher Collins syndrome."
				pmid:  "41036210"
				year:  2025
			},
			{
				title: "Long-read DNA and RNA sequencing reveal an intronic retrotransposon insertion in TCOF1 causing Treacher Collins syndrome."
				pmid:  "41017149"
				year:  2026
			},
			{
				title: "Gene-environment interactions modulate the phenotype severity in mouse models of congenital craniofacial syndromes."
				pmid:  "40699891"
				year:  2025
			},
		]
	}
	"TFAP2A": {
		_in_pubmed:     true
		pubmed_gene_id: "7020"
		pubmed_total:   95
		pubmed_recent:  24
		pubmed_papers: [
			{
				title: "The Molecular Mechanism of Craniofacial Cartilage Deformity Induced by High Glucose in Zebrafish."
				pmid:  "41020809"
				year:  2025
			},
			{
				title: "Branchiooculofacial Syndrome."
				pmid:  "21634087"
				year:  1993
			},
			{
				title: "Identification of functional non-coding variants associated with orofacial cleft."
				pmid:  "40670354"
				year:  2025
			},
		]
	}
	"TFAP2B": {
		_in_pubmed:     true
		pubmed_gene_id: "7021"
		pubmed_total:   45
		pubmed_recent:  14
		pubmed_papers: [
			{
				title: "Comparative analysis of neural crest development in the chick and mouse."
				pmid:  "39716593"
				year:  2025
			},
			{
				title: "Comparative Analysis of Neural Crest Development in the Chick and Mouse."
				pmid:  "39574664"
				year:  2024
			},
			{
				title: "Transcriptional programs of Pitx2 and Tfap2a/Tfap2b controlling lineage specification of mandibular epithelium during tooth initiation."
				pmid:  "39052671"
				year:  2024
			},
		]
	}
	"TGFBR1": {
		_in_pubmed:     true
		pubmed_gene_id: "7046"
		pubmed_total:   82
		pubmed_recent:  28
		pubmed_papers: [
			{
				title: "Effects of miR-128-3p on Renal Inflammation in a Rat Periodontitis Model."
				pmid:  "41440335"
				year:  2025
			},
			{
				title: "Distinctive Amelogenesis Imperfecta in Loeys-Dietz Syndrome Type II."
				pmid:  "40261094"
				year:  2025
			},
			{
				title: "Administration of Porphyromonas gingivalis in pregnant mice enhances glycolysis and histone lactylation/ADAM17 leading to cleft palate in offspring."
				pmid:  "40075093"
				year:  2025
			},
		]
	}
	"TGFBR2": {
		_in_pubmed:     true
		pubmed_gene_id: "7048"
		pubmed_total:   121
		pubmed_recent:  33
		pubmed_papers: [
			{
				title: "Development of a zebrafish model of Loeys-Dietz syndrome through tgfbr2b knockdown."
				pmid:  "41629640"
				year:  2026
			},
			{
				title: "Variability, asymmetry and sexual dimorphism in craniofacial anomalies in Loeys-Dietz syndrome 2: geometric morphometric analysis in mice."
				pmid:  "41519957"
				year:  2026
			},
			{
				title: "Genetic analysis and functional assessment of a TGFBR2 variant in micrognathia and cleft palate."
				pmid:  "40489498"
				year:  2025
			},
		]
	}
	"TWIST1": {
		_in_pubmed:     true
		pubmed_gene_id: "7291"
		pubmed_total:   289
		pubmed_recent:  80
		pubmed_papers: [
			{
				title: "Loss of Twist1 leads to disruption of ciliary length, endocytic vesicle dynamics, and cell-cell junctions during neural tube formation."
				pmid:  "41493130"
				year:  2026
			},
			{
				title: "TWIST1 Modulates Cilia Length, Endocytic Vesicle Dynamics, and Cell-Cell Junctions during Neural Tube Morphogenesis."
				pmid:  "41256626"
				year:  2025
			},
			{
				title: "Distinct Intrinsic and Extrinsic Factors Differentially Regulate Skeletal Stem Cells in Calvaria Versus Long Bones During Bone Regeneration."
				pmid:  "41096681"
				year:  2025
			},
		]
	}
	"TWIST2": {
		_in_pubmed:     true
		pubmed_gene_id: "117581"
		pubmed_total:   36
		pubmed_recent:  10
		pubmed_papers: [
			{
				title: "Acellular dental pulp and allogeneic cells for strategic pulp regeneration."
				pmid:  "41687189"
				year:  2026
			},
			{
				title: "Gene-by-Environment Interactions Involving Maternal Exposures with Orofacial Cleft Risk in Filipinos."
				pmid:  "40869924"
				year:  2025
			},
			{
				title: "Gene-by-environment interactions involving maternal exposures with orofacial cleft risk in Filipinos."
				pmid:  "39830233"
				year:  2024
			},
		]
	}
	"TYR": {
		_in_pubmed:     true
		pubmed_gene_id: "7299"
		pubmed_total:   221
		pubmed_recent:  46
		pubmed_papers: [
			{
				title: "Histogenesis of Atypical Teratoid Rhabdoid Tumors: Anatomical and Embryological Perspectives."
				pmid:  "41514521"
				year:  2025
			},
			{
				title: "Targeting the melanocytes of the inner ear: A comparison of different CreER lines."
				pmid:  "41397511"
				year:  2026
			},
			{
				title: "Polyphenol-Microbiota Interactions in Atherosclerosis: The Role of Hydroxytyrosol and Tyrosol in Modulating Inflammation and Oxidative Stress."
				pmid:  "41374074"
				year:  2025
			},
		]
	}
	"TYRP1": {
		_in_pubmed:     true
		pubmed_gene_id: "7306"
		pubmed_total:   28
		pubmed_recent:  5
		pubmed_papers: [
			{
				title: "Modulatory effects of oxytocin on normal human cultured melanocyte proliferation, migration, and melanogenesis."
				pmid:  "39388927"
				year:  2024
			},
			{
				title: "Differentiation of cultured hair follicle neural crest stem cells into functional melanocytes."
				pmid:  "39170163"
				year:  2024
			},
			{
				title: "Reverse Genetic Approach to Identify Regulators of Pigmentation using Zebrafish."
				pmid:  "35312674"
				year:  2022
			},
		]
	}
	"WNT1": {
		_in_pubmed:     true
		pubmed_gene_id: "7471"
		pubmed_total:   430
		pubmed_recent:  105
		pubmed_papers: [
			{
				title: "Loss of SPECC1L in cranial neural crest cells results in increased hedgehog signaling and frontonasal dysplasia."
				pmid:  "41657552"
				year:  2026
			},
			{
				title: "NR6A1 is essential for neural crest cell specification, formation and survival."
				pmid:  "41611698"
				year:  2026
			},
			{
				title: "Engineered cyclic peptide targeting ITGA5 disrupts tumor-stroma interaction to overcome desmoplasia and resistance in pancreatic ductal adenocarcinoma."
				pmid:  "41584360"
				year:  2026
			},
		]
	}
	"WNT3A": {
		_in_pubmed:     true
		pubmed_gene_id: "89780"
		pubmed_total:   231
		pubmed_recent:  74
		pubmed_papers: [
			{
				title: "Wnt3a promotes in situ dentin formation through NKD1-MSX1 axis-mediated odontogenic differentiation of dental pulp stem cells."
				pmid:  "41526338"
				year:  2026
			},
			{
				title: "From Bench to Bedside: Translating Research on miR-138 miR-195-5p and Long Non-Coding RNA H19 into Therapeutic Applications of Orthodontic Tooth Movement."
				pmid:  "41328182"
				year:  2025
			},
			{
				title: "Amelogenin Promotes Periodontal Bone Regeneration by Inducing Bone Marrow Mesenchymal Stem Cell Homing."
				pmid:  "40842050"
				year:  2025
			},
		]
	}
	"ZEB2": {
		_in_pubmed:     true
		pubmed_gene_id: "9839"
		pubmed_total:   55
		pubmed_recent:  20
		pubmed_papers: [
			{
				title: "Multiple cell types guided by neurocytes orchestrate horn bud initiation in dairy goats."
				pmid:  "40597626"
				year:  2025
			},
			{
				title: "Anti-metastatic potential of flavonoids for the treatment of cancers: focus on epithelial-mesenchymal transition (EMT) process."
				pmid:  "40434422"
				year:  2025
			},
			{
				title: "Classic Mowat-Wilson Syndrome."
				pmid:  "20301585"
				year:  1993
			},
		]
	}
	"ZIC1": {
		_in_pubmed:     true
		pubmed_gene_id: "7545"
		pubmed_total:   57
		pubmed_recent:  10
		pubmed_papers: [
			{
				title: "Unilateral craniosynostosis associated with ZIC1 gene mutation: a case report."
				pmid:  "41523225"
				year:  2026
			},
			{
				title: "Dynamic and non-uniform expression of key transcription factors provides novel insights into the emergence of neural crest cells at the neural plate border."
				pmid:  "41256729"
				year:  2025
			},
			{
				title: "MicroRNA miR-196a controls neural crest patterning by repressing immature neural ectoderm programs in Xenopus embryos."
				pmid:  "40939754"
				year:  2025
			},
		]
	}
}
