package lacuene

// Protein structures: AlphaFold predictions + PDB experimental structures.
// Sources: AlphaFold EBI API, RCSB PDB Search API
// Generated by normalizers/from_structures.py -- 95 genes

genes: {
	"ADAM10": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 80.1
		pdb_count: 3
		has_experimental_structure: true
	}
	"ALDH1A2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 95.8
		pdb_count: 7
		has_experimental_structure: true
	}
	"AXIN2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 60.5
		pdb_count: 1
		has_experimental_structure: true
	}
	"BMP2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 79.6
		pdb_count: 21
		has_experimental_structure: true
	}
	"BMP4": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 78.5
		pdb_count: 0
		has_experimental_structure: false
	}
	"BMP7": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 76.2
		pdb_count: 4
		has_experimental_structure: true
	}
	"CDH11": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 77.7
		pdb_count: 0
		has_experimental_structure: false
	}
	"CDH2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 79.4
		pdb_count: 0
		has_experimental_structure: false
	}
	"CDH6": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 78.7
		pdb_count: 1
		has_experimental_structure: true
	}
	"CHD7": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 46.1
		pdb_count: 3
		has_experimental_structure: true
	}
	"CTNNB1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 81.1
		pdb_count: 47
		has_experimental_structure: true
	}
	"CXCR4": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 82.2
		pdb_count: 30
		has_experimental_structure: true
	}
	"DCT": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 89.1
		pdb_count: 1
		has_experimental_structure: true
	}
	"DLL1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 75.0
		pdb_count: 1
		has_experimental_structure: true
	}
	"DLX2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 58.5
		pdb_count: 0
		has_experimental_structure: false
	}
	"DLX3": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 60.2
		pdb_count: 1
		has_experimental_structure: true
	}
	"DLX5": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 60.7
		pdb_count: 2
		has_experimental_structure: true
	}
	"DLX6": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 75.1
		pdb_count: 4
		has_experimental_structure: true
	}
	"ECE1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 90.9
		pdb_count: 1
		has_experimental_structure: true
	}
	"EDN1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 65.2
		pdb_count: 17
		has_experimental_structure: true
	}
	"EDN3": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 55.9
		pdb_count: 1
		has_experimental_structure: true
	}
	"EDNRA": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 74.4
		pdb_count: 4
		has_experimental_structure: true
	}
	"EDNRB": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 75.0
		pdb_count: 17
		has_experimental_structure: true
	}
	"ERBB3": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 72.4
		pdb_count: 23
		has_experimental_structure: true
	}
	"ETS1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 65.4
		pdb_count: 21
		has_experimental_structure: true
	}
	"EVC": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 73.6
		pdb_count: 0
		has_experimental_structure: false
	}
	"FGF8": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 81.1
		pdb_count: 1
		has_experimental_structure: true
	}
	"FGFR1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 73.9
		pdb_count: 81
		has_experimental_structure: true
	}
	"FGFR2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 73.9
		pdb_count: 59
		has_experimental_structure: true
	}
	"FGFR3": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 74.2
		pdb_count: 13
		has_experimental_structure: true
	}
	"FN1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 69.6
		pdb_count: 68
		has_experimental_structure: true
	}
	"FOXD3": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 55.0
		pdb_count: 0
		has_experimental_structure: false
	}
	"GATA4": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 57.2
		pdb_count: 3
		has_experimental_structure: true
	}
	"GBX2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 69.2
		pdb_count: 2
		has_experimental_structure: true
	}
	"GDNF": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 75.0
		pdb_count: 4
		has_experimental_structure: true
	}
	"GFRA1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 74.1
		pdb_count: 1
		has_experimental_structure: true
	}
	"HAND1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 64.9
		pdb_count: 0
		has_experimental_structure: false
	}
	"HAND2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 66.4
		pdb_count: 0
		has_experimental_structure: false
	}
	"IRF6": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 73.5
		pdb_count: 0
		has_experimental_structure: false
	}
	"ITGB1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 85.9
		pdb_count: 21
		has_experimental_structure: true
	}
	"JAG1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 73.1
		pdb_count: 7
		has_experimental_structure: true
	}
	"KIT": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 78.2
		pdb_count: 52
		has_experimental_structure: true
	}
	"LEF1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 57.0
		pdb_count: 0
		has_experimental_structure: false
	}
	"MEF2C": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 55.7
		pdb_count: 0
		has_experimental_structure: false
	}
	"MITF": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 60.8
		pdb_count: 12
		has_experimental_structure: true
	}
	"MMP2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 89.8
		pdb_count: 14
		has_experimental_structure: true
	}
	"MMP9": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 82.1
		pdb_count: 29
		has_experimental_structure: true
	}
	"MSX1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 64.2
		pdb_count: 0
		has_experimental_structure: false
	}
	"MSX2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 67.4
		pdb_count: 0
		has_experimental_structure: false
	}
	"MYCN": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 60.2
		pdb_count: 2
		has_experimental_structure: true
	}
	"NF1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 87.2
		pdb_count: 26
		has_experimental_structure: true
	}
	"NGFR": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 75.9
		pdb_count: 7
		has_experimental_structure: true
	}
	"NKX2-5": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 62.6
		pdb_count: 4
		has_experimental_structure: true
	}
	"NOTCH1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 59.6
		pdb_count: 29
		has_experimental_structure: true
	}
	"NOTCH2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 59.4
		pdb_count: 2
		has_experimental_structure: true
	}
	"NR2F1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 75.2
		pdb_count: 1
		has_experimental_structure: true
	}
	"NR2F2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 76.8
		pdb_count: 1
		has_experimental_structure: true
	}
	"NRP1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 79.1
		pdb_count: 25
		has_experimental_structure: true
	}
	"PAX3": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 63.9
		pdb_count: 1
		has_experimental_structure: true
	}
	"PAX6": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 68.4
		pdb_count: 2
		has_experimental_structure: true
	}
	"PAX7": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 62.0
		pdb_count: 0
		has_experimental_structure: false
	}
	"PHOX2B": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 59.8
		pdb_count: 5
		has_experimental_structure: true
	}
	"PLXNA2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 84.5
		pdb_count: 1
		has_experimental_structure: true
	}
	"PMEL": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 68.4
		pdb_count: 20
		has_experimental_structure: true
	}
	"RAC1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 93.8
		pdb_count: 74
		has_experimental_structure: true
	}
	"RARA": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 78.1
		pdb_count: 14
		has_experimental_structure: true
	}
	"RET": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 78.8
		pdb_count: 34
		has_experimental_structure: true
	}
	"RHOA": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 93.6
		pdb_count: 128
		has_experimental_structure: true
	}
	"RUNX2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 58.6
		pdb_count: 4
		has_experimental_structure: true
	}
	"SEMA3A": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 84.8
		pdb_count: 0
		has_experimental_structure: false
	}
	"SEMA3C": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 85.7
		pdb_count: 0
		has_experimental_structure: false
	}
	"SHH": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 78.4
		pdb_count: 20
		has_experimental_structure: true
	}
	"SMAD1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 81.2
		pdb_count: 10
		has_experimental_structure: true
	}
	"SNAI1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 57.7
		pdb_count: 8
		has_experimental_structure: true
	}
	"SNAI2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 64.4
		pdb_count: 0
		has_experimental_structure: false
	}
	"SOX10": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 55.8
		pdb_count: 0
		has_experimental_structure: false
	}
	"SOX2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 59.8
		pdb_count: 13
		has_experimental_structure: true
	}
	"SOX5": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 57.6
		pdb_count: 0
		has_experimental_structure: false
	}
	"SOX8": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 58.1
		pdb_count: 0
		has_experimental_structure: false
	}
	"SOX9": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 56.0
		pdb_count: 1
		has_experimental_structure: true
	}
	"TBX1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 68.2
		pdb_count: 1
		has_experimental_structure: true
	}
	"TBX5": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 62.7
		pdb_count: 4
		has_experimental_structure: true
	}
	"TCOF1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 41.3
		pdb_count: 0
		has_experimental_structure: false
	}
	"TFAP2A": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 67.9
		pdb_count: 3
		has_experimental_structure: true
	}
	"TFAP2B": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 66.1
		pdb_count: 1
		has_experimental_structure: true
	}
	"TGFBR1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 84.2
		pdb_count: 44
		has_experimental_structure: true
	}
	"TGFBR2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 81.0
		pdb_count: 22
		has_experimental_structure: true
	}
	"TWIST1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 66.3
		pdb_count: 2
		has_experimental_structure: true
	}
	"TWIST2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 73.0
		pdb_count: 0
		has_experimental_structure: false
	}
	"TYR": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 89.9
		pdb_count: 1
		has_experimental_structure: true
	}
	"TYRP1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 91.7
		pdb_count: 13
		has_experimental_structure: true
	}
	"WNT1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 85.9
		pdb_count: 0
		has_experimental_structure: false
	}
	"WNT3A": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 88.3
		pdb_count: 4
		has_experimental_structure: true
	}
	"ZEB2": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 48.2
		pdb_count: 1
		has_experimental_structure: true
	}
	"ZIC1": {
		_in_structures: true
		has_alphafold: true
		alphafold_confidence: 54.1
		pdb_count: 0
		has_experimental_structure: false
	}
}
