#!/usr/bin/env python3
"""
Normalizer: OMIM -> model/omim.cue

Reads pre-researched OMIM disease association data from data/omim/omim_subset.json
and emits a CUE file with Mendelian phenotype entries for 20 neural crest genes.

OMIM requires API registration, so this normalizer uses a bundled data subset
rather than live API calls. To refresh: update data/omim/omim_subset.json.

Usage:
    python3 normalizers/from_omim.py
"""

import json
import sys
from pathlib import Path

# Ensure normalizers/ is importable
sys.path.insert(0, str(Path(__file__).resolve().parent))
from genes import GENES

# Paths relative to repo root
REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "data" / "omim" / "omim_subset.json"
OUTPUT_FILE = REPO_ROOT / "model" / "omim.cue"


def load_omim_data() -> dict:
    """Load the bundled OMIM subset JSON."""
    if not DATA_FILE.exists():
        print(f"ERROR: Missing data file: {DATA_FILE}", file=sys.stderr)
        print("Run with bundled data in data/omim/omim_subset.json", file=sys.stderr)
        sys.exit(1)

    with open(DATA_FILE) as f:
        data = json.load(f)

    return data["genes"]


def format_cue_string(s: str) -> str:
    """Escape a string for CUE literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def generate_cue(omim_data: dict) -> str:
    """Generate CUE source from OMIM data, keyed by HGNC symbol."""
    lines = [
        "package lacuene",
        "",
        "// OMIM: Mendelian disease associations for neural crest genes.",
        "// Source: data/omim/omim_subset.json (bundled subset, hand-curated from omim.org)",
        f"// Generated by normalizers/from_omim.py — {len(omim_data)} genes",
        "",
        "genes: {",
    ]

    # Emit in canonical order (sorted HGNC symbols)
    for symbol in sorted(GENES.keys()):
        if symbol not in omim_data:
            print(f"WARNING: {symbol} not in OMIM subset, skipping", file=sys.stderr)
            continue

        entry = omim_data[symbol]
        gene_info = GENES[symbol]
        omim_id = gene_info["omim"]  # Use the canonical OMIM ID from genes.py
        title = format_cue_string(entry["title"])
        syndromes = entry.get("syndromes", [])
        inheritance = entry.get("inheritance")

        lines.append(f'\t"{symbol}": {{')
        lines.append(f"\t\t_in_omim: true")
        lines.append(f'\t\tomim_id:  "{omim_id}"')
        lines.append(f'\t\tomim_title: "{title}"')

        # Syndromes list (may be empty for genes with no Mendelian phenotype)
        if syndromes:
            syndrome_strs = []
            for s in syndromes:
                name = format_cue_string(s["name"])
                mim = s["mim"]
                syndrome_strs.append(f'"{name}, {mim}"')

            if len(syndrome_strs) == 1:
                lines.append(f"\t\tomim_syndromes: [{syndrome_strs[0]}]")
            else:
                lines.append(f"\t\tomim_syndromes: [")
                for ss in syndrome_strs:
                    lines.append(f"\t\t\t{ss},")
                lines.append(f"\t\t]")

            # Inheritance mode
            if inheritance:
                lines.append(f'\t\tinheritance: "{inheritance}"')

        lines.append(f"\t}}")

    lines.append("}")
    lines.append("")  # trailing newline

    return "\n".join(lines)


def main():
    omim_data = load_omim_data()

    # Cross-check: every gene in GENES should be in omim_data
    missing = set(GENES.keys()) - set(omim_data.keys())
    if missing:
        print(f"WARNING: genes missing from OMIM subset: {sorted(missing)}", file=sys.stderr)

    extra = set(omim_data.keys()) - set(GENES.keys())
    if extra:
        print(f"WARNING: extra genes in OMIM subset not in GENES: {sorted(extra)}", file=sys.stderr)

    cue_source = generate_cue(omim_data)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(cue_source)

    # Stats
    with_syndromes = sum(1 for g in omim_data.values() if g.get("syndromes"))
    without = sum(1 for g in omim_data.values() if not g.get("syndromes"))
    total_syndromes = sum(len(g.get("syndromes", [])) for g in omim_data.values())

    print(f"Wrote {OUTPUT_FILE} ({len(omim_data)} genes, "
          f"{with_syndromes} with syndromes, {without} without, "
          f"{total_syndromes} total syndrome associations)")


if __name__ == "__main__":
    main()
